use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use heck::ToSnakeCase;

use crate::Result;
use crate::codegen::writer::CodeWriter;
use crate::codegen::{CodegenConfig, OutputMode};
use crate::display::preview::PreviewFile;

use super::{GeneratedRust, RustStruct};

/// Writer for Rust code generation
#[derive(Default)]
pub struct RustWriter;

impl RustWriter {
    const HEADER: &'static str = "//! Generated by shki - DO NOT EDIT";

    pub fn new() -> Self {
        Self {}
    }

    fn format_imports(&self, imports: &[String]) -> String {
        let mut output = String::new();

        if !imports.is_empty() {
            for import in imports {
                writeln!(output, "{}", import).expect("writing to string should not fail");
            }
            output.push('\n');
        }

        output
    }

    fn write_type_file(&self, file_path: &Path, imports: &[String], content: &str) -> Result<()> {
        let mut file = fs::File::create(file_path)?;
        write!(file, "{}", self.format_type_file(imports, content))?;
        Ok(())
    }

    fn format_type_file(&self, imports: &[String], content: &str) -> String {
        let mut output = String::new();

        writeln!(output, "{}", Self::HEADER).expect("writing to string should not fail");
        output.push('\n');
        output.push_str(&self.format_imports(imports));
        writeln!(output, "{}", content).expect("writing to string should not fail");

        output
    }

    /// Write mod.rs file for module modes
    fn write_mod_file(&self, mod_path: &Path, mod_entries: &[ModuleEntry]) -> Result<()> {
        let mut mod_file = fs::File::create(mod_path)?;
        write!(mod_file, "{}", self.format_mod_file(mod_entries))?;
        Ok(())
    }

    fn format_mod_file(&self, mod_entries: &[ModuleEntry]) -> String {
        let mut output = String::new();

        writeln!(output, "{}", Self::HEADER).expect("writing to string should not fail");
        output.push('\n');

        for entry in mod_entries {
            writeln!(output, "pub mod {};", entry.module_name)
                .expect("writing to string should not fail");
        }
        output.push('\n');

        for entry in mod_entries {
            writeln!(output, "pub use {}::*;", entry.module_name)
                .expect("writing to string should not fail");
        }

        output
    }

    /// Build the `use` path for a sibling generated type.
    ///
    /// File organization differs by output mode, so the relative path to a
    /// sibling type does too:
    /// - `Module`: types are flat files under one module (`out/<type>.rs`), so a
    ///   sibling is `super::<module>::<Type>`.
    /// - `Modules`: each type's definition lives in a nested module
    ///   (`out/<type>/_def.rs`), so a sibling is two levels up and reached
    ///   through the top-level re-export: `super::super::<Type>`.
    fn type_import(&self, type_name: &str, mode: OutputMode) -> String {
        match mode {
            OutputMode::Modules => format!("use super::super::{};", type_name),
            _ => format!("use super::{}::{};", type_name.to_snake_case(), type_name),
        }
    }

    /// Collect imports needed for a struct
    fn collect_struct_imports(
        &self,
        rust_struct: &RustStruct,
        code: &GeneratedRust,
        mode: OutputMode,
    ) -> Vec<String> {
        let mut imports = BTreeSet::new();

        for field in &rust_struct.fields {
            for rust_enum in code.enums.values() {
                if field.rust_type.contains(&rust_enum.name) {
                    imports.insert(self.type_import(&rust_enum.name, mode));
                }
            }

            // Structs may reference other generated structs (e.g. a column
            // whose type is a composite type). Import those too, skipping the
            // struct's own module.
            for other in code.structs.values() {
                if other.name != rust_struct.name && field.rust_type.contains(&other.name) {
                    imports.insert(self.type_import(&other.name, mode));
                }
            }

            if field.rust_type.contains("chrono::") {
                imports.insert("use chrono;".to_string());
            }
            if field.rust_type.contains("uuid::") {
                imports.insert("use uuid;".to_string());
            }
            if field.rust_type.contains("serde_json::") {
                imports.insert("use serde_json;".to_string());
            }
        }

        imports.into_iter().collect()
    }

    /// The per-type `mod.rs`: a thin, user-editable index that mounts the
    /// generated `_def.rs` and re-exports it.
    ///
    /// This file is written only when absent, so hand-written code added here
    /// (extra `impl` blocks, additional `mod` declarations, supporting types)
    /// survives regeneration. The generated definition is isolated in `_def.rs`,
    /// which is always overwritten. Splitting them this way also keeps the
    /// directory name from being mirrored as a file name (clippy's
    /// `module_inception`).
    fn format_module_index(&self) -> String {
        concat!(
            "//! Generated once by shki - safe to edit.\n",
            "//!\n",
            "//! shki will not overwrite this file on regeneration. The generated\n",
            "//! type lives in `_def.rs` and is re-exported below; add custom `impl`\n",
            "//! blocks, extra modules, or supporting code here.\n",
            "\n",
            "mod _def;\n",
            "pub use _def::*;\n",
        )
        .to_string()
    }

    fn collect_generated_items(
        &self,
        code: &GeneratedRust,
        mode: OutputMode,
    ) -> Vec<GeneratedItem> {
        code.enums
            .values()
            .map(|e| {
                GeneratedItem::new(
                    e.name.to_snake_case(),
                    e.name.clone(),
                    vec![],
                    e.to_string_pretty(),
                )
            })
            .chain(code.structs.values().map(|s| {
                GeneratedItem::new(
                    s.name.to_snake_case(),
                    s.name.clone(),
                    self.collect_struct_imports(s, code, mode),
                    s.to_string_pretty(),
                )
            }))
            .collect()
    }
}

struct ModuleEntry {
    module_name: String,
    type_name: String,
}

struct GeneratedItem {
    module_name: String,
    type_name: String,
    imports: Vec<String>,
    content: String,
}

impl GeneratedItem {
    fn new(
        module_name: impl Into<String>,
        type_name: impl Into<String>,
        imports: Vec<String>,
        content: String,
    ) -> Self {
        Self {
            module_name: module_name.into(),
            type_name: type_name.into(),
            imports,
            content,
        }
    }
}

impl ModuleEntry {
    fn new(module_name: impl Into<String>, type_name: impl Into<String>) -> Self {
        Self {
            module_name: module_name.into(),
            type_name: type_name.into(),
        }
    }
}

impl CodeWriter for RustWriter {
    type GeneratedCode = GeneratedRust;

    fn write_single_file(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let file_path = self.output_file_path(output_dir);
        let mut file = fs::File::create(&file_path)?;
        write!(file, "{}", self.single_file_contents(code))?;

        Ok(vec![file_path])
    }

    fn write_single_module(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let items = self.collect_generated_items(code, OutputMode::Module);
        let mut written_files = Vec::new();
        let mut mod_entries = Vec::new();

        for item in &items {
            let file_path =
                output_dir.join(format!("{}.{}", item.module_name, self.file_extension()));
            self.write_type_file(&file_path, &item.imports, &item.content)?;

            written_files.push(file_path);
            mod_entries.push(ModuleEntry::new(&item.module_name, &item.type_name));
        }

        let mod_path = output_dir.join("mod.rs");
        self.write_mod_file(&mod_path, &mod_entries)?;
        written_files.push(mod_path);

        Ok(written_files)
    }

    fn write_modules(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let types = self.collect_generated_items(code, OutputMode::Modules);

        let mut written_files = Vec::new();

        for type_info in &types {
            let module_dir = output_dir.join(&type_info.module_name);
            fs::create_dir_all(&module_dir)?;

            // The generated type definition is isolated in _def.rs, which is
            // always overwritten on regeneration.
            let def_path = module_dir.join(format!("_def.{}", self.file_extension()));
            self.write_type_file(&def_path, &type_info.imports, &type_info.content)?;
            written_files.push(def_path);

            // mod.rs is a thin, user-editable index that mounts _def.rs. It is
            // written only when absent, so any custom code (or extra files added
            // to this directory and wired up here) survives regeneration.
            let mod_path = module_dir.join("mod.rs");
            if !mod_path.exists() {
                let mut mod_file = fs::File::create(&mod_path)?;
                write!(mod_file, "{}", self.format_module_index())?;
                written_files.push(mod_path);
            }
        }

        let mod_defs = types
            .into_iter()
            .map(|t| ModuleEntry::new(t.module_name, t.type_name))
            .collect::<Vec<_>>();

        self.write_mod_file(output_dir.join("mod.rs").as_path(), &mod_defs)?;

        Ok(written_files)
    }

    fn single_file_contents(&self, code: &Self::GeneratedCode) -> String {
        let mut output = String::new();

        writeln!(output, "{}", Self::HEADER).expect("writing to string should not fail");
        output.push('\n');
        output.push_str(&self.format_imports(&code.required_imports()));

        // Single-file output keeps every type in one file, so the per-item
        // cross-module imports are unused here.
        for item in self.collect_generated_items(code, OutputMode::File) {
            writeln!(output, "{}", item.content).expect("writing to string should not fail");
        }

        output
    }

    fn preview_files(
        &self,
        code: &Self::GeneratedCode,
        config: &CodegenConfig,
    ) -> Vec<PreviewFile> {
        let ext = self.file_extension();

        match config.format() {
            OutputMode::File => vec![PreviewFile::new(
                format!("{}.{}", self.default_filename(), ext),
                self.single_file_contents(code),
            )],
            OutputMode::Module => {
                let items = self.collect_generated_items(code, OutputMode::Module);
                let mut files: Vec<PreviewFile> = items
                    .iter()
                    .map(|item| {
                        PreviewFile::new(
                            format!("{}.{}", item.module_name, ext),
                            self.format_type_file(&item.imports, &item.content),
                        )
                    })
                    .collect();

                let mod_entries: Vec<ModuleEntry> = items
                    .iter()
                    .map(|item| ModuleEntry::new(&item.module_name, &item.type_name))
                    .collect();
                files.push(PreviewFile::new(
                    "mod.rs",
                    self.format_mod_file(&mod_entries),
                ));
                files
            }
            OutputMode::Modules => {
                let items = self.collect_generated_items(code, OutputMode::Modules);
                let mut files: Vec<PreviewFile> = items
                    .iter()
                    .flat_map(|item| {
                        [
                            PreviewFile::new(
                                format!("{}/_def.{}", item.module_name, ext),
                                self.format_type_file(&item.imports, &item.content),
                            ),
                            PreviewFile::new(
                                format!("{}/mod.{}", item.module_name, ext),
                                self.format_module_index(),
                            ),
                        ]
                    })
                    .collect();

                let mod_entries: Vec<ModuleEntry> = items
                    .iter()
                    .map(|item| ModuleEntry::new(&item.module_name, &item.type_name))
                    .collect();
                files.push(PreviewFile::new(
                    "mod.rs",
                    self.format_mod_file(&mod_entries),
                ));
                files
            }
        }
    }

    fn syntax_language(&self) -> &str {
        "rust"
    }

    fn file_extension(&self) -> &str {
        "rs"
    }

    fn default_filename(&self) -> &str {
        "models"
    }
}

#[cfg(test)]
mod tests {
    use super::super::{RustEnum, RustField};
    use super::*;

    fn field(name: &str, rust_type: &str) -> RustField {
        RustField {
            name: name.to_string(),
            db_name: name.to_string(),
            rust_type: rust_type.to_string(),
            nullable: false,
            primary_key: false,
            unique: false,
            comment: None,
        }
    }

    fn rust_struct(name: &str, fields: Vec<RustField>) -> RustStruct {
        RustStruct {
            name: name.to_string(),
            table_name: name.to_string(),
            fields,
            derives: vec![],
            attributes: vec![],
            serde: false,
            sqlx: false,
            comment: None,
        }
    }

    fn rust_enum(name: &str) -> RustEnum {
        RustEnum {
            name: name.to_string(),
            db_name: name.to_string(),
            variants: vec![],
            derives: vec![],
            attributes: vec![],
            serde: false,
            sqlx: false,
            comment: None,
        }
    }

    /// Build a `GeneratedRust` with an enum, a composite-derived struct, and a
    /// table struct whose fields reference both plus external crates.
    fn sample_code() -> (GeneratedRust, RustStruct) {
        let mut code = GeneratedRust::default();
        code.enums
            .insert("user_status".to_string(), rust_enum("UserStatus"));
        code.structs.insert(
            "addresses".to_string(),
            rust_struct("Address", vec![field("street", "String")]),
        );

        let user = rust_struct(
            "User",
            vec![
                field("id", "uuid::Uuid"),
                field("status", "UserStatus"),
                field("home_address", "Option<Address>"),
                field("created_at", "chrono::DateTime<chrono::Utc>"),
                field("data", "serde_json::Value"),
                field("name", "String"),
            ],
        );
        code.structs.insert("users".to_string(), user.clone());

        (code, user)
    }

    #[test]
    fn module_format_imports_reference_siblings_one_level_up() {
        // Flat `Module` layout: each type is a file directly under the output
        // root, so a sibling is reached via `super::<module>::<Type>`.
        let (code, user) = sample_code();
        let imports = RustWriter::new().collect_struct_imports(&user, &code, OutputMode::Module);

        assert!(imports.contains(&"use super::user_status::UserStatus;".to_string()));
        assert!(imports.contains(&"use super::address::Address;".to_string()));
        assert!(imports.contains(&"use chrono;".to_string()));
        assert!(imports.contains(&"use uuid;".to_string()));
        assert!(imports.contains(&"use serde_json;".to_string()));
    }

    #[test]
    fn modules_format_imports_reference_siblings_two_levels_up() {
        // Nested `Modules` layout: each type's definition lives in
        // `out/<type>/_def.rs`, so a sibling is two levels up and reached through
        // the top-level re-export: `super::super::<Type>`.
        let (code, user) = sample_code();
        let imports = RustWriter::new().collect_struct_imports(&user, &code, OutputMode::Modules);

        assert!(imports.contains(&"use super::super::UserStatus;".to_string()));
        assert!(imports.contains(&"use super::super::Address;".to_string()));
        // External crate imports are unaffected by the module layout.
        assert!(imports.contains(&"use chrono;".to_string()));
        assert!(imports.contains(&"use uuid;".to_string()));
        assert!(!imports.iter().any(|i| i.contains("super::address")));
    }

    #[test]
    fn collect_struct_imports_skips_plain_scalar_fields() {
        let (code, _) = sample_code();
        // The composite struct only has a `String` field, so it needs no imports.
        let address = &code.structs["addresses"];
        let imports =
            RustWriter::new().collect_struct_imports(address, &code, OutputMode::Module);

        assert!(imports.is_empty());
    }

    #[test]
    fn collect_struct_imports_does_not_import_self() {
        // A composite/struct that references itself must not emit a `use super`
        // import for its own module, in either module layout.
        let mut code = GeneratedRust::default();
        let node = rust_struct(
            "Node",
            vec![field("parent", "Option<Node>"), field("label", "String")],
        );
        code.structs.insert("nodes".to_string(), node.clone());

        for mode in [OutputMode::Module, OutputMode::Modules] {
            let imports = RustWriter::new().collect_struct_imports(&node, &code, mode);
            assert!(imports.is_empty(), "self-import leaked in {mode:?} mode");
        }
    }

    #[test]
    fn single_module_imports_are_emitted_in_generated_files() {
        // End-to-end through the single-module writer: the file for the `User`
        // struct must carry the one-level `use super::...` imports.
        let (code, _) = sample_code();
        let dir =
            std::env::temp_dir().join(format!("shki_writer_module_test_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);

        let written = RustWriter::new()
            .write_single_module(&code, &dir, &CodegenConfig::default())
            .expect("module generation should succeed");

        let user_file = written
            .iter()
            .find(|p| p.file_name().and_then(|n| n.to_str()) == Some("user.rs"))
            .expect("user.rs should be generated");
        let contents = fs::read_to_string(user_file).expect("user.rs should be readable");

        assert!(contents.contains("use super::user_status::UserStatus;"));
        assert!(contents.contains("use super::address::Address;"));
        assert!(contents.contains("use uuid;"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn modules_imports_are_emitted_in_generated_files() {
        // End-to-end through the nested-modules writer: the `User` type's
        // definition lives in `<dir>/user/_def.rs` and reaches sibling types two
        // levels up via `super::super::<Type>`; `<dir>/user/mod.rs` is a thin
        // index that mounts _def.rs.
        let (code, _) = sample_code();
        let dir =
            std::env::temp_dir().join(format!("shki_writer_modules_test_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);

        let written = RustWriter::new()
            .write_modules(&code, &dir, &CodegenConfig::default())
            .expect("modules generation should succeed");

        let def_file = written
            .iter()
            .find(|p| p.ends_with("user/_def.rs"))
            .expect("user/_def.rs should be generated");
        let def = fs::read_to_string(def_file).expect("user/_def.rs should be readable");

        assert!(def.contains("pub struct User"));
        assert!(def.contains("use super::super::UserStatus;"));
        assert!(def.contains("use super::super::Address;"));
        assert!(!def.contains("use super::address::Address;"));
        // The directory name is not mirrored as a file name.
        assert!(!written.iter().any(|p| p.ends_with("user/user.rs")));

        // mod.rs is the thin, user-editable index that mounts _def.rs.
        let mod_file = written
            .iter()
            .find(|p| p.ends_with("user/mod.rs"))
            .expect("user/mod.rs should be generated");
        let mod_rs = fs::read_to_string(mod_file).expect("user/mod.rs should be readable");
        assert!(mod_rs.contains("mod _def;"));
        assert!(mod_rs.contains("pub use _def::*;"));
        // The user-editable index carries no DO-NOT-EDIT header.
        assert!(!mod_rs.contains("DO NOT EDIT"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn modules_mod_file_is_preserved_but_def_is_overwritten() {
        // Regenerating must always refresh _def.rs but never clobber a
        // hand-edited mod.rs.
        let (code, _) = sample_code();
        let dir = std::env::temp_dir()
            .join(format!("shki_writer_modules_mod_test_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);

        let writer = RustWriter::new();
        writer
            .write_modules(&code, &dir, &CodegenConfig::default())
            .expect("first generation should succeed");

        // Hand-edit mod.rs (e.g. add a custom impl block) and clobber _def.rs to
        // prove it is regenerated.
        let mod_path = dir.join("user/mod.rs");
        let def_path = dir.join("user/_def.rs");
        fs::write(
            &mod_path,
            "mod _def;\npub use _def::*;\nimpl User {\n    fn custom() {}\n}\n",
        )
        .expect("should be able to edit mod.rs");
        fs::write(&def_path, "// stale\n").expect("should be able to clobber _def.rs");

        writer
            .write_modules(&code, &dir, &CodegenConfig::default())
            .expect("second generation should succeed");

        let mod_rs = fs::read_to_string(&mod_path).expect("mod.rs should still exist");
        assert!(mod_rs.contains("fn custom()"), "custom mod.rs was clobbered");

        let def = fs::read_to_string(&def_path).expect("_def.rs should still exist");
        assert!(def.contains("pub struct User"), "_def.rs was not regenerated");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn preview_file_mode_renders_a_single_labeled_file() {
        let (code, _) = sample_code();
        let config = CodegenConfig::default(); // defaults to OutputMode::File
        let preview = RustWriter::new().format_preview(&code, &config, true);

        assert!(preview.contains("1 file(s):"));
        assert!(preview.contains("models.rs"));
        assert!(preview.contains("pub struct User"));
        // Single-file output is not split, so there is no mod.rs entry.
        assert!(!preview.contains("mod.rs"));
    }

    #[test]
    fn preview_module_mode_renders_separate_flat_files() {
        let (code, _) = sample_code();
        let config = CodegenConfig::default().mode(Some(OutputMode::Module));
        let preview = RustWriter::new().format_preview(&code, &config, true);

        // One file per type plus the module root, each under its own path label.
        assert!(preview.contains("user.rs"));
        assert!(preview.contains("address.rs"));
        assert!(preview.contains("user_status.rs"));
        assert!(preview.contains("mod.rs"));
        // Flat layout reaches siblings one level up.
        assert!(preview.contains("use super::address::Address;"));
    }

    #[test]
    fn preview_modules_mode_renders_nested_def_and_mod_files() {
        let (code, _) = sample_code();
        let config = CodegenConfig::default().mode(Some(OutputMode::Modules));
        let preview = RustWriter::new().format_preview(&code, &config, true);

        // The generated definition lives in each type's _def.rs, alongside a thin
        // user-editable mod.rs that mounts it.
        assert!(preview.contains("user/_def.rs"));
        assert!(preview.contains("user/mod.rs"));
        assert!(preview.contains("address/_def.rs"));
        // The directory name is not mirrored as a file name.
        assert!(!preview.contains("user/user.rs"));
        assert!(preview.contains("mod _def;"));
        // Nested layout reaches siblings two levels up via the root re-export.
        assert!(preview.contains("use super::super::Address;"));
        assert!(!preview.contains("use super::address::Address;"));
    }
}
