use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use heck::ToSnakeCase;

use crate::Result;
use crate::codegen::CodegenConfig;
use crate::codegen::generator::apply_name_pattern;
use crate::codegen::writer::CodeWriter;

use super::{GeneratedRust, RustStruct};

/// Writer for Rust code generation
#[derive(Default)]
pub struct RustWriter;

impl RustWriter {
    const HEADER: &'static str = "//! Generated by shki - DO NOT EDIT";

    pub fn new() -> Self {
        Self {}
    }

    fn format_imports(&self, imports: &[String]) -> String {
        let mut output = String::new();

        if !imports.is_empty() {
            for import in imports {
                writeln!(output, "{}", import).expect("writing to string should not fail");
            }
            output.push('\n');
        }

        output
    }

    fn write_type_file(&self, file_path: &Path, imports: &[String], content: &str) -> Result<()> {
        let mut file = fs::File::create(file_path)?;
        write!(file, "{}", self.format_type_file(imports, content))?;
        Ok(())
    }

    fn format_type_file(&self, imports: &[String], content: &str) -> String {
        let mut output = String::new();

        writeln!(output, "{}", Self::HEADER).expect("writing to string should not fail");
        output.push('\n');
        output.push_str(&self.format_imports(imports));
        writeln!(output, "{}", content).expect("writing to string should not fail");

        output
    }

    /// Write mod.rs file for module modes
    fn write_mod_file(&self, mod_path: &Path, mod_entries: &[ModuleEntry]) -> Result<()> {
        let mut mod_file = fs::File::create(mod_path)?;
        write!(mod_file, "{}", self.format_mod_file(mod_entries))?;
        Ok(())
    }

    fn format_mod_file(&self, mod_entries: &[ModuleEntry]) -> String {
        let mut output = String::new();

        writeln!(output, "{}", Self::HEADER).expect("writing to string should not fail");
        output.push('\n');

        for entry in mod_entries {
            writeln!(output, "mod {};", entry.module_name)
                .expect("writing to string should not fail");
        }
        output.push('\n');

        for entry in mod_entries {
            writeln!(
                output,
                "pub use {}::{};",
                entry.module_name, entry.type_name
            )
            .expect("writing to string should not fail");
        }

        output
    }

    /// Collect imports needed for a struct
    fn collect_struct_imports(
        &self,
        rust_struct: &RustStruct,
        code: &GeneratedRust,
    ) -> Vec<String> {
        let mut imports = BTreeSet::new();

        for field in &rust_struct.fields {
            for rust_enum in code.enums.values() {
                if field.rust_type.contains(&rust_enum.name) {
                    let module_name = rust_enum.name.to_snake_case();
                    imports.insert(format!("use super::{}::{};", module_name, rust_enum.name));
                }
            }

            if field.rust_type.contains("chrono::") {
                imports.insert("use chrono;".to_string());
            }
            if field.rust_type.contains("uuid::") {
                imports.insert("use uuid;".to_string());
            }
            if field.rust_type.contains("serde_json::") {
                imports.insert("use serde_json;".to_string());
            }
        }

        imports.into_iter().collect()
    }

    /// Create the module directory structure for Modules mode
    fn ensure_module_structure(
        &self,
        module_dir: &Path,
        module_name: &str,
        type_name: &str,
        impl_name: &str,
    ) -> Result<()> {
        fs::create_dir_all(module_dir)?;

        let module_path = module_dir.join("mod.rs");
        if !module_path.exists() {
            let mut file = fs::File::create(&module_path)?;
            write!(
                file,
                "{}\n\npub mod {};\npub use {}::*;\npub mod {};\npub use {}::*;\n",
                Self::HEADER,
                module_name,
                module_name,
                impl_name,
                impl_name
            )?;
        }

        let impl_path = module_dir.join(format!("{}.rs", impl_name));
        if !impl_path.exists() {
            let mut file = fs::File::create(&impl_path)?;
            writeln!(file, "//! Implementation details for {}", type_name)?;
        }

        Ok(())
    }

    fn collect_generated_items(&self, code: &GeneratedRust) -> Vec<GeneratedItem> {
        code.enums
            .values()
            .map(|e| {
                GeneratedItem::new(
                    e.name.to_snake_case(),
                    e.name.clone(),
                    vec![],
                    e.to_string_pretty(),
                )
            })
            .chain(code.structs.values().map(|s| {
                GeneratedItem::new(
                    s.name.to_snake_case(),
                    s.name.clone(),
                    self.collect_struct_imports(s, code),
                    s.to_string_pretty(),
                )
            }))
            .collect()
    }
}

struct ModuleEntry {
    module_name: String,
    type_name: String,
}

struct GeneratedItem {
    module_name: String,
    type_name: String,
    imports: Vec<String>,
    content: String,
}

impl GeneratedItem {
    fn new(
        module_name: impl Into<String>,
        type_name: impl Into<String>,
        imports: Vec<String>,
        content: String,
    ) -> Self {
        Self {
            module_name: module_name.into(),
            type_name: type_name.into(),
            imports,
            content,
        }
    }
}

impl ModuleEntry {
    fn new(module_name: impl Into<String>, type_name: impl Into<String>) -> Self {
        Self {
            module_name: module_name.into(),
            type_name: type_name.into(),
        }
    }
}

impl CodeWriter for RustWriter {
    type GeneratedCode = GeneratedRust;

    fn write_single_file(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let file_path = self.output_file_path(output_dir);
        let mut file = fs::File::create(&file_path)?;
        write!(file, "{}", self.format_preview(code))?;

        Ok(vec![file_path])
    }

    fn write_single_module(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let items = self.collect_generated_items(code);
        let mut written_files = Vec::new();
        let mut mod_entries = Vec::new();

        for item in &items {
            let file_path =
                output_dir.join(format!("{}.{}", item.module_name, self.file_extension()));
            self.write_type_file(&file_path, &item.imports, &item.content)?;

            written_files.push(file_path);
            mod_entries.push(ModuleEntry::new(&item.module_name, &item.type_name));
        }

        let mod_path = output_dir.join("mod.rs");
        self.write_mod_file(&mod_path, &mod_entries)?;
        written_files.push(mod_path);

        Ok(written_files)
    }

    fn write_modules(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let types = self.collect_generated_items(code);

        let mut written_files = Vec::new();

        for type_info in &types {
            let pattern = Some(config.impl_pattern.clone().unwrap_or("{}_impl".to_string()));
            let impl_name = apply_name_pattern(&type_info.module_name, pattern.as_deref());

            let module_dir = output_dir.join(&type_info.module_name);

            self.ensure_module_structure(
                &module_dir,
                &type_info.module_name,
                &type_info.type_name,
                &impl_name,
            )?;

            let file_path = module_dir.join(format!(
                "{}.{}",
                type_info.module_name,
                self.file_extension()
            ));
            self.write_type_file(&file_path, &type_info.imports, &type_info.content)?;

            written_files.push(file_path);
        }

        let mod_defs = types
            .into_iter()
            .map(|t| ModuleEntry::new(t.module_name, t.type_name))
            .collect::<Vec<_>>();

        self.write_mod_file(output_dir.join("mod.rs").as_path(), &mod_defs)?;

        Ok(written_files)
    }

    fn format_preview(&self, code: &Self::GeneratedCode) -> String {
        let mut output = String::new();

        writeln!(output, "{}", Self::HEADER).expect("writing to string should not fail");
        output.push('\n');
        output.push_str(&self.format_imports(&code.required_imports()));

        for item in self.collect_generated_items(code) {
            writeln!(output, "{}", item.content).expect("writing to string should not fail");
        }

        output
    }

    fn file_extension(&self) -> &str {
        "rs"
    }

    fn default_filename(&self) -> &str {
        "models"
    }
}
