[package]
name = "shki"
version = "0.4.1"
edition = "2024"
description = "Declarative database schema management and migration tool in Rust"
license = "MIT"
repository = "https://github.com/dk0d/shki"
homepage = "https://shki.sh"
keywords = ["database", "schema", "migration", "postgresql", "mysql", "sqlite"]
categories = ["database", "command-line-utilities"]

[[bin]]
name = "shki"
path = "src/main.rs"

[lib]
name = "shki"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.100"
chrono = { version = "0.4.43", features = ["serde"] }
clap = { version = "4.5.55", features = ["derive", "string", "env"] }
colored = "3.1.1"
figment = { version = "0.10.19", features = ["env", "toml", "serde_json"] }
indexmap = { version = "2.13.0", features = ["serde"] }
thiserror = "2.0.18"

# Serialization and Deserialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "0.9.11"

# Database Drivers
sqlx = { version = "0.8.6", features = [
  "any",
  "postgres",
  "runtime-tokio",
  "sqlite",
  "mysql",
  "uuid",
  "chrono",
  "ipnet",
  "json",
] }
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1.20.0", features = ["v4", "v7", "serde"] }
glob = "0.3.3"
petname = "2.0.2"
tabled = { version = "0.20.0", features = ["ansi", "derive"] }
sea-query = "1.0.0-rc.1"

# Code generation
heck = "0.5.0"
proc-macro2 = "1.0.106"
quote = "1.0.44"
pluralizer = "0.5.0"
prettyplease = "0.2.37"
syn = "2.0.114"
dialoguer = { version = "0.12.0", features = ["fuzzy-matcher", "fuzzy-select"] }
dotenvy = { version = "0.15.7", features = ["clap", "cli"] }
sha2 = "0.10"
serde_yaml = "0.9.34"
enum_dispatch = "0.3.13"
async-trait = "0.1.89"
inquire = { version = "0.9.4", features = ["chrono"] }
bat = "0.26.1"
postgresql_embedded = { version = "0.20.2", features = ["tokio"] }
ariadne = "0.6.0"

[dev-dependencies]
tempfile = "3.24.0"
testcontainers = { version = "0.27.3", features = ["reusable-containers"] }
testcontainers-modules = { version = "0.15.0", features = [
  "mysql",
  "postgres",
] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
