//! TypeScript file writer
//!
//! Writes generated TypeScript code to files in various output modes.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{fs, io::Write as _};

use heck::ToSnakeCase;

use crate::Result;
use crate::codegen::writer::CodeWriter;
use crate::codegen::{CodegenConfig, OutputMode};
use crate::display::preview::PreviewFile;

use super::{GeneratedTypeScript, TypeScriptInterface, TypescriptFlavor};

/// Writer for TypeScript code generation
#[derive(Default)]
pub struct TypeScriptWriter;

impl TypeScriptWriter {
    const HEADER: &'static str = "// Generated by shki - DO NOT EDIT";

    /// Collect imports needed for an interface.
    ///
    /// Properties may reference generated enums or other generated interfaces
    /// (e.g. a column whose type is a composite type), each of which lives in
    /// its own module and must be imported. The interface's own module is
    /// skipped to avoid a self-import.
    fn collect_interface_imports(
        &self,
        ts_interface: &TypeScriptInterface,
        code: &GeneratedTypeScript,
    ) -> Vec<String> {
        let mut imports = Vec::new();

        let mut push_import = |type_name: &str| {
            let module_name = type_name.to_snake_case();
            match ts_interface.flavor {
                TypescriptFlavor::Type => imports.push(format!(
                    "import type {{ {} }} from './{}';",
                    type_name, module_name
                )),
                TypescriptFlavor::Interface => imports.push(format!(
                    "import {{ {} }} from './{}';",
                    type_name, module_name
                )),
            };
        };

        for property in &ts_interface.properties {
            for ts_enum in code.enums.values() {
                if property.ts_type.contains(&ts_enum.name) {
                    push_import(&ts_enum.name);
                }
            }

            for other in code.interfaces.values() {
                if other.name != ts_interface.name && property.ts_type.contains(&other.name) {
                    push_import(&other.name);
                }
            }
        }

        imports.sort();
        imports.dedup();
        imports
    }

    fn format_imports(&self, imports: &[String]) -> String {
        let mut output = String::new();

        if !imports.is_empty() {
            for import in imports {
                writeln!(output, "{}", import).expect("writing to string should not fail");
            }
            output.push('\n');
        }

        output
    }

    fn write_type_file(&self, file_path: &Path, imports: &[String], content: &str) -> Result<()> {
        let mut file = fs::File::create(file_path)?;
        write!(file, "{}", self.format_type_file(imports, content))?;
        Ok(())
    }

    fn format_type_file(&self, imports: &[String], content: &str) -> String {
        let mut output = String::new();

        writeln!(output, "{}", Self::HEADER).expect("writing to string should not fail");
        output.push('\n');
        output.push_str(&self.format_imports(imports));
        writeln!(output, "{}", content).expect("writing to string should not fail");

        output
    }

    /// Write an index.ts file that re-exports all types
    fn write_index_file(&self, index_path: &Path, exports: &[ExportEntry]) -> Result<()> {
        let mut file = fs::File::create(index_path)?;
        write!(file, "{}", self.format_index_file(exports))?;
        Ok(())
    }

    fn format_index_file(&self, exports: &[ExportEntry]) -> String {
        let mut output = String::new();

        writeln!(output, "{}", Self::HEADER).expect("writing to string should not fail");
        output.push('\n');

        for export in exports {
            writeln!(
                output,
                "export {{ {} }} from './{}';",
                export.type_name, export.module_name
            )
            .expect("writing to string should not fail");
        }

        output
    }

    fn collect_generated_items(&self, code: &GeneratedTypeScript) -> Vec<GeneratedItem> {
        code.enums
            .values()
            .map(|e| {
                GeneratedItem::new(
                    e.name.to_snake_case(),
                    e.name.clone(),
                    vec![],
                    e.to_string(),
                )
            })
            .chain(code.interfaces.values().map(|i| {
                GeneratedItem::new(
                    i.name.to_snake_case(),
                    i.name.clone(),
                    self.collect_interface_imports(i, code),
                    i.to_string(),
                )
            }))
            .collect()
    }
}

struct ExportEntry {
    module_name: String,
    type_name: String,
}

impl ExportEntry {
    fn new(module_name: impl Into<String>, type_name: impl Into<String>) -> Self {
        Self {
            module_name: module_name.into(),
            type_name: type_name.into(),
        }
    }
}

struct GeneratedItem {
    module_name: String,
    type_name: String,
    imports: Vec<String>,
    content: String,
}

impl GeneratedItem {
    fn new(
        module_name: impl Into<String>,
        type_name: impl Into<String>,
        imports: Vec<String>,
        content: String,
    ) -> Self {
        Self {
            module_name: module_name.into(),
            type_name: type_name.into(),
            imports,
            content,
        }
    }
}

impl CodeWriter for TypeScriptWriter {
    type GeneratedCode = GeneratedTypeScript;

    fn write_single_file(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let file_path = self.output_file_path(output_dir);
        let mut file = fs::File::create(&file_path)?;
        write!(file, "{}", self.single_file_contents(code))?;

        println!("Generated TypeScript types: {}", file_path.display());

        Ok(vec![file_path])
    }

    fn write_single_module(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let items = self.collect_generated_items(code);
        let mut written_files = Vec::new();
        let mut exports = Vec::new();

        for item in &items {
            let file_path =
                output_dir.join(format!("{}.{}", item.module_name, self.file_extension()));
            self.write_type_file(&file_path, &item.imports, &item.content)?;
            written_files.push(file_path);
            exports.push(ExportEntry::new(&item.module_name, &item.type_name));
        }

        // Write index.ts
        let index_path = output_dir.join("index.ts");
        self.write_index_file(&index_path, &exports)?;
        written_files.push(index_path);

        println!(
            "Generated {} TypeScript files in {}",
            written_files.len(),
            output_dir.display()
        );

        Ok(written_files)
    }

    fn write_modules(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        println!("Warning: TypeScript codegen treats modules mode as single-module");
        self.write_single_module(code, output_dir, config)
    }

    fn single_file_contents(&self, code: &Self::GeneratedCode) -> String {
        let mut output = String::new();

        writeln!(output, "{}", Self::HEADER).expect("writing to string should not fail");
        output.push('\n');

        for item in self.collect_generated_items(code) {
            writeln!(output, "{}", item.content).expect("writing to string should not fail");
        }

        output
    }

    fn preview_files(
        &self,
        code: &Self::GeneratedCode,
        config: &CodegenConfig,
    ) -> Vec<PreviewFile> {
        let ext = self.file_extension();

        // TypeScript only distinguishes single-file from a flat module
        // directory (nested `Modules` is treated as a single module), so any
        // non-`File` mode previews the per-type files plus the `index.ts`.
        if config.format() == OutputMode::File {
            return vec![PreviewFile::new(
                format!("{}.{}", self.default_filename(), ext),
                self.single_file_contents(code),
            )];
        }

        let items = self.collect_generated_items(code);
        let mut files: Vec<PreviewFile> = items
            .iter()
            .map(|item| {
                PreviewFile::new(
                    format!("{}.{}", item.module_name, ext),
                    self.format_type_file(&item.imports, &item.content),
                )
            })
            .collect();

        let exports: Vec<ExportEntry> = items
            .iter()
            .map(|item| ExportEntry::new(&item.module_name, &item.type_name))
            .collect();
        files.push(PreviewFile::new(
            "index.ts",
            self.format_index_file(&exports),
        ));
        files
    }

    fn syntax_language(&self) -> &str {
        "typescript"
    }

    fn file_extension(&self) -> &str {
        "ts"
    }

    fn default_filename(&self) -> &str {
        "models"
    }
}

#[cfg(test)]
mod tests {
    use super::super::{TypeScriptEnum, TypeScriptProperty};
    use super::*;

    fn property(name: &str, ts_type: &str) -> TypeScriptProperty {
        TypeScriptProperty {
            name: name.to_string(),
            db_name: name.to_string(),
            ts_type: ts_type.to_string(),
            nullable: false,
            comment: None,
        }
    }

    fn interface(name: &str, properties: Vec<TypeScriptProperty>) -> TypeScriptInterface {
        TypeScriptInterface {
            name: name.to_string(),
            table_name: name.to_string(),
            properties,
            comment: None,
            flavor: TypescriptFlavor::Interface,
        }
    }

    fn ts_enum(name: &str) -> TypeScriptEnum {
        TypeScriptEnum {
            name: name.to_string(),
            db_name: name.to_string(),
            members: vec![],
            comment: None,
        }
    }

    fn sample_code() -> (GeneratedTypeScript, TypeScriptInterface) {
        let mut code = GeneratedTypeScript::default();
        code.enums
            .insert("user_status".to_string(), ts_enum("UserStatus"));
        code.interfaces.insert(
            "addresses".to_string(),
            interface("Address", vec![property("street", "string")]),
        );

        let user = interface(
            "User",
            vec![
                property("status", "UserStatus"),
                property("homeAddress", "Address"),
                property("name", "string"),
            ],
        );
        code.interfaces.insert("users".to_string(), user.clone());

        (code, user)
    }

    #[test]
    fn collect_interface_imports_references_generated_enums_and_interfaces() {
        let (code, user) = sample_code();
        let imports = TypeScriptWriter.collect_interface_imports(&user, &code);

        assert!(imports.contains(&"import { UserStatus } from './user_status';".to_string()));
        assert!(imports.contains(&"import { Address } from './address';".to_string()));
    }

    #[test]
    fn collect_interface_imports_skips_plain_scalar_properties() {
        let (code, _) = sample_code();
        let address = &code.interfaces["addresses"];
        let imports = TypeScriptWriter.collect_interface_imports(address, &code);

        assert!(imports.is_empty());
    }

    #[test]
    fn collect_interface_imports_does_not_import_self() {
        let mut code = GeneratedTypeScript::default();
        let node = interface(
            "Node",
            vec![property("parent", "Node"), property("label", "string")],
        );
        code.interfaces.insert("nodes".to_string(), node.clone());

        let imports = TypeScriptWriter.collect_interface_imports(&node, &code);
        assert!(imports.is_empty());
    }

    #[test]
    fn type_flavor_uses_import_type() {
        let (mut code, _) = sample_code();
        // Re-flavor the referencing interface as a `type` alias.
        let mut user = interface("User", vec![property("status", "UserStatus")]);
        user.flavor = TypescriptFlavor::Type;
        code.interfaces.insert("users".to_string(), user.clone());

        let imports = TypeScriptWriter.collect_interface_imports(&user, &code);
        assert!(imports.contains(&"import type { UserStatus } from './user_status';".to_string()));
    }

    #[test]
    fn module_imports_are_emitted_in_generated_files() {
        let (code, _) = sample_code();
        let dir = std::env::temp_dir().join(format!("shki_ts_writer_test_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);

        let written = TypeScriptWriter
            .write_single_module(&code, &dir, &CodegenConfig::default())
            .expect("module generation should succeed");

        let user_file = written
            .iter()
            .find(|p| p.file_name().and_then(|n| n.to_str()) == Some("user.ts"))
            .expect("user.ts should be generated");
        let contents = fs::read_to_string(user_file).expect("user.ts should be readable");

        assert!(contents.contains("import { UserStatus } from './user_status';"));
        assert!(contents.contains("import { Address } from './address';"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn preview_file_mode_renders_a_single_labeled_file() {
        let (code, _) = sample_code();
        let config = CodegenConfig::default(); // defaults to OutputMode::File
        let preview = TypeScriptWriter.format_preview(&code, &config, true);

        assert!(preview.contains("1 file(s):"));
        assert!(preview.contains("models.ts"));
        assert!(preview.contains("interface User"));
        assert!(!preview.contains("index.ts"));
    }

    #[test]
    fn preview_module_mode_renders_separate_files_with_index() {
        let (code, _) = sample_code();
        let config = CodegenConfig::default().mode(Some(OutputMode::Module));
        let preview = TypeScriptWriter.format_preview(&code, &config, true);

        assert!(preview.contains("user.ts"));
        assert!(preview.contains("address.ts"));
        assert!(preview.contains("index.ts"));
        assert!(preview.contains("import { Address } from './address';"));
    }
}
