//! Render described queries as Rust functions that wrap them with sqlx.
//!
//! Generated functions use sqlx's runtime API (`query_as` / `query`), not the
//! compile-time macros: shki has already type-checked the query against the
//! Shadow Database, so the generated code simply executes it. Result rows reuse
//! the schema-generated struct when a query returns a table wholesale, and
//! otherwise get a synthesized `<Name>Row` struct. See
//! `docs/adr/0001-typed-query-codegen.md`.

use heck::{ToSnakeCase, ToUpperCamelCase};
use indexmap::IndexMap;
use proc_macro2::{Ident, Literal, Span, TokenStream};
use quote::quote;

use crate::codegen::CodegenConfig;
use crate::codegen::generator::CodeGenerator;
use crate::codegen::lang::rust::{RustField, RustGenerator, RustStruct, make_safe_field_name};
use crate::models::iden::Iden;
use crate::schema::{CompositeType, DbEnum};
use crate::snapshots::Snapshot;

use super::describe::{DescribedQuery, ParamBinding, QueryParam, QueryResult, ResultColumn};
use super::parse::Cardinality;

/// Render a full Rust module for all described queries.
///
/// `models_module`, when set, is emitted as `use <models_module>::*;` so the
/// generated functions can reference schema structs/enums (e.g. `User`) reused
/// from the schema codegen output.
pub fn generate_rust_module(
    queries: &[DescribedQuery],
    snapshot: &Snapshot,
    config: &CodegenConfig,
    models_module: Option<&str>,
) -> String {
    let generator = RustGenerator::new();
    let enums = snapshot.enums();
    let composites = snapshot.composite_types();

    let mut items: Vec<TokenStream> = Vec::new();

    if let Some(path) = models_module {
        let use_path: TokenStream = format!("{}::*", path)
            .parse()
            .expect("models module path should be a valid Rust path");
        items.push(quote! {
            #[allow(unused_imports)]
            use #use_path;
        });
    }

    // Emit each shared pagination type only when a query actually needs it.
    if queries.iter().any(uses_limit_offset_pagination) {
        items.push(limit_offset_pagination_types());
    }
    if queries.iter().any(uses_cursor_pagination) {
        items.push(cursor_pagination_types());
    }

    for query in queries {
        if let QueryResult::Row { columns } = &query.result {
            let row_struct =
                build_row_struct(&generator, query, columns, &enums, &composites, config);
            items.push(row_struct.to_tokens());
        }
        items.push(build_fn(&generator, query, config, &enums, &composites));
    }

    let body = quote! { #(#items)* };

    let header = "// Code generated by shki query codegen. DO NOT EDIT.\n\
                  #![allow(clippy::all, dead_code)]\n\n";
    format!("{}{}", header, format_tokens(body))
}

/// Does this query use limit/offset pagination (the `Pagination` + `Page` types)?
fn uses_limit_offset_pagination(query: &DescribedQuery) -> bool {
    query.params.iter().any(|param| {
        matches!(
            param.binding,
            ParamBinding::PageLimit | ParamBinding::PageOffset
        )
    })
}

/// Does this query use keyset/cursor pagination (the `CursorPagination` type)?
fn uses_cursor_pagination(query: &DescribedQuery) -> bool {
    query
        .params
        .iter()
        .any(|param| matches!(param.binding, ParamBinding::Cursor { .. }))
}

/// The shared `Pagination` input and `Page<T>` result used by limit/offset
/// `:batch` queries.
fn limit_offset_pagination_types() -> TokenStream {
    quote! {
        /// Limit/offset pagination input shared by generated `:batch` queries.
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub struct Pagination {
            pub limit: i64,
            pub offset: i64,
        }

        impl Pagination {
            pub fn new(limit: i64, offset: i64) -> Self {
                Self { limit, offset }
            }

            /// Pagination for the next page: same limit, offset advanced by limit.
            pub fn next(&self) -> Self {
                Self {
                    limit: self.limit,
                    offset: self.offset + self.limit,
                }
            }
        }

        /// One page of results from a `:batch` query.
        #[derive(Debug, Clone)]
        pub struct Page<T> {
            pub items: Vec<T>,
            pub pagination: Pagination,
        }

        impl<T> Page<T> {
            /// Pagination to request the next page.
            pub fn next(&self) -> Pagination {
                self.pagination.next()
            }
        }
    }
}

/// The shared `CursorPagination` input used by keyset `:batch` queries. `K` is
/// the cursor key — a single type for a one-column keyset, or a tuple for a
/// multi-column keyset (e.g. `(i32, DateTime<Utc>)`).
fn cursor_pagination_types() -> TokenStream {
    quote! {
        /// Keyset cursor input shared by generated `:batch :keyset` queries.
        ///
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub struct CursorPagination<K> {
            pub key: K,
        }

        impl<K> CursorPagination<K> {
            pub fn new(key: K) -> Self {
                Self { key }
            }
        }

        /// One page of results from a keyset `:batch` query.
        #[derive(Debug, Clone)]
        pub struct KeysetPage<T, K> {
            pub items: Vec<T>,
            pub next: Option<CursorPagination<K>>,
        }
    }
}

/// Synthesized row struct name for a query, e.g. `active_users` -> `ActiveUsersRow`.
fn row_struct_name(query_name: &str) -> String {
    format!("{}Row", query_name.to_upper_camel_case())
}

fn build_row_struct(
    generator: &RustGenerator,
    query: &DescribedQuery,
    columns: &[ResultColumn],
    enums: &IndexMap<Iden, DbEnum>,
    composites: &IndexMap<Iden, CompositeType>,
    config: &CodegenConfig,
) -> RustStruct {
    let fields = columns
        .iter()
        .map(|col| RustField {
            name: make_safe_field_name(&col.name),
            db_name: col.name.clone(),
            rust_type: generator.sql_type_to_rust(
                &col.data_type,
                col.nullable,
                enums,
                composites,
                config,
            ),
            nullable: col.nullable,
            primary_key: false,
            unique: false,
            comment: None,
        })
        .collect();

    RustStruct {
        name: row_struct_name(&query.spec.name),
        table_name: query.spec.name.clone(),
        fields,
        derives: config.struct_derives.clone(),
        attributes: config.struct_attributes.clone(),
        serde: config.serde(),
        // Query result rows are decoded via sqlx, so FromRow is mandatory here
        // regardless of the `sqlx` codegen toggle.
        sqlx: true,
        comment: None,
    }
}

/// Build the function's argument declarations and the ordered `.bind(...)` calls.
///
/// Parameters bound from the shared `Pagination` (batch limit/offset) are bound
/// but not exposed as arguments; everything else becomes a named or positional
/// (`argN`) argument.
fn build_args_and_binds(
    generator: &RustGenerator,
    params: &[QueryParam],
    enums: &IndexMap<Iden, DbEnum>,
    composites: &IndexMap<Iden, CompositeType>,
    config: &CodegenConfig,
) -> (Vec<TokenStream>, Vec<TokenStream>) {
    let mut arg_decls = Vec::new();
    let mut binds = Vec::new();

    // A single-key cursor binds `cursor.key`; a multi-key cursor binds tuple
    // fields `cursor.key.0`, `cursor.key.1`, ...
    let keyset_len = params
        .iter()
        .filter(|param| matches!(param.binding, ParamBinding::Cursor { .. }))
        .count();

    for (idx, param) in params.iter().enumerate() {
        match &param.binding {
            ParamBinding::Arg(name) => {
                let ident = match name {
                    Some(name) => ident_from(&make_safe_field_name(name)),
                    None => Ident::new(&format!("arg{}", idx + 1), Span::call_site()),
                };
                let ty: TokenStream = generator
                    .sql_type_to_rust(&param.data_type, false, enums, composites, config)
                    .parse()
                    .expect("mapped param type should be valid Rust");
                arg_decls.push(quote! { #ident: #ty });
                binds.push(quote! { .bind(#ident) });
            }
            ParamBinding::PageLimit => binds.push(quote! { .bind(page.limit) }),
            ParamBinding::PageOffset => binds.push(quote! { .bind(page.offset) }),
            ParamBinding::Cursor { key_index, .. } => {
                // Cursor keys live behind `&CursorPagination`; clone so non-Copy
                // key types (e.g. String) can be bound by value.
                let access = if keyset_len <= 1 {
                    quote! { cursor.key.clone() }
                } else {
                    let field = syn::Index::from(*key_index);
                    quote! { cursor.key.#field.clone() }
                };
                binds.push(quote! { .bind(#access) });
            }
        }
    }

    (arg_decls, binds)
}

/// The cursor key type for a keyset query: the single key's type, or a tuple of
/// the key types in cursor-key order. `None` when the query has no keyset.
fn cursor_key_type(
    generator: &RustGenerator,
    params: &[QueryParam],
    enums: &IndexMap<Iden, DbEnum>,
    composites: &IndexMap<Iden, CompositeType>,
    config: &CodegenConfig,
) -> Option<String> {
    let mut keys: Vec<(usize, &QueryParam)> = params
        .iter()
        .filter_map(|param| match param.binding {
            ParamBinding::Cursor { key_index, .. } => Some((key_index, param)),
            _ => None,
        })
        .collect();
    if keys.is_empty() {
        return None;
    }
    keys.sort_by_key(|(key_index, _)| *key_index);

    let types: Vec<String> = keys
        .iter()
        .map(|(_, param)| {
            generator.sql_type_to_rust(&param.data_type, false, enums, composites, config)
        })
        .collect();

    Some(if types.len() == 1 {
        types[0].clone()
    } else {
        format!("({})", types.join(", "))
    })
}

/// Field accesses for the next cursor, in keyset annotation order.
fn cursor_key_fields(params: &[QueryParam]) -> Vec<Ident> {
    let mut keys: Vec<(usize, Ident)> = params
        .iter()
        .filter_map(|param| match &param.binding {
            ParamBinding::Cursor { key_index, field } => {
                Some((*key_index, ident_from(&make_safe_field_name(field))))
            }
            _ => None,
        })
        .collect();
    keys.sort_by_key(|(key_index, _)| *key_index);
    keys.into_iter().map(|(_, field)| field).collect()
}

fn build_fn(
    generator: &RustGenerator,
    query: &DescribedQuery,
    config: &CodegenConfig,
    enums: &IndexMap<Iden, DbEnum>,
    composites: &IndexMap<Iden, CompositeType>,
) -> TokenStream {
    let fn_name = Ident::new(&query.spec.name.to_snake_case(), Span::call_site());
    let sql = Literal::string(&query.sql);
    let doc = format!(
        " `{}` ({}). Generated from {}.",
        query.spec.name,
        cardinality_label(query.spec.cardinality),
        query.spec.source_file.display()
    );

    let (mut arg_decls, binds) =
        build_args_and_binds(generator, &query.params, enums, composites, config);
    let executor = if query.spec.transaction {
        arg_decls.insert(
            0,
            quote! { transaction: &mut sqlx::Transaction<'_, sqlx::Postgres> },
        );
        quote! { &mut **transaction }
    } else {
        arg_decls.insert(0, quote! { executor: E });
        quote! { executor }
    };
    let generic = (!query.spec.transaction).then(|| quote! { <'e, E> });
    let where_clause = (!query.spec.transaction).then(|| {
        quote! {
            where
                E: sqlx::PgExecutor<'e>,
        }
    });

    // `:batch` adds a pagination input after the data arguments: a keyset cursor
    // when the query has a `:keyset` annotation, otherwise the limit/offset page.
    let cursor_key = cursor_key_type(generator, &query.params, enums, composites, config);
    if query.spec.cardinality == Cardinality::Batch {
        match &cursor_key {
            Some(key) => {
                let key_ty: TokenStream =
                    key.parse().expect("cursor key type should be valid Rust");
                arg_decls.push(quote! { cursor: &CursorPagination<#key_ty> });
            }
            None => arg_decls.push(quote! { page: &Pagination }),
        }
    }

    if let QueryResult::Exec = &query.result {
        return quote! {
            #[doc = #doc]
            pub async fn #fn_name #generic(#(#arg_decls),*) -> sqlx::Result<u64>
            #where_clause
            {
                let result = sqlx::query(#sql)
                    #(#binds)*
                    .execute(#executor)
                    .await?;
                Ok(result.rows_affected())
            }
        };
    }

    let elem_name = match &query.result {
        QueryResult::Reuse { table_name } => generator.transform_struct_name(table_name, config),
        QueryResult::Row { .. } => row_struct_name(&query.spec.name),
        QueryResult::Exec => unreachable!("exec handled above"),
    };
    let elem: TokenStream = elem_name
        .parse()
        .expect("result element type should be valid Rust");

    match query.spec.cardinality {
        Cardinality::One => quote! {
            #[doc = #doc]
            pub async fn #fn_name #generic(#(#arg_decls),*) -> sqlx::Result<Option<#elem>>
            #where_clause
            {
                sqlx::query_as::<_, #elem>(#sql)
                    #(#binds)*
                    .fetch_optional(#executor)
                    .await
            }
        },
        Cardinality::Many => quote! {
            #[doc = #doc]
            pub async fn #fn_name #generic(#(#arg_decls),*) -> sqlx::Result<Vec<#elem>>
            #where_clause
            {
                sqlx::query_as::<_, #elem>(#sql)
                    #(#binds)*
                    .fetch_all(#executor)
                    .await
            }
        },
        Cardinality::Batch if cursor_key.is_some() => {
            let cursor_key: TokenStream = cursor_key
                .as_ref()
                .expect("keyset batch has a cursor key")
                .parse()
                .expect("cursor key type should be valid Rust");
            let fields = cursor_key_fields(&query.params);
            let next_key = if fields.len() == 1 {
                let field = &fields[0];
                quote! { row.#field.clone() }
            } else {
                quote! { (#(row.#fields.clone()),*) }
            };
            quote! {
                #[doc = #doc]
                pub async fn #fn_name #generic(#(#arg_decls),*) -> sqlx::Result<KeysetPage<#elem, #cursor_key>>
                #where_clause
                {
                    let items = sqlx::query_as::<_, #elem>(#sql)
                        #(#binds)*
                        .fetch_all(#executor)
                        .await?;
                    let next = items.last().map(|row| CursorPagination::new(#next_key));
                    Ok(KeysetPage { items, next })
                }
            }
        }
        // Limit/offset `:batch`: return a `Page` carrying the pagination used.
        Cardinality::Batch => quote! {
            #[doc = #doc]
            pub async fn #fn_name #generic(#(#arg_decls),*) -> sqlx::Result<Page<#elem>>
            #where_clause
            {
                let items = sqlx::query_as::<_, #elem>(#sql)
                    #(#binds)*
                    .fetch_all(#executor)
                    .await?;
                Ok(Page {
                    items,
                    pagination: Pagination {
                        limit: page.limit,
                        offset: page.offset,
                    },
                })
            }
        },
        Cardinality::Exec => unreachable!("exec handled above"),
    }
}

/// Build an identifier, honoring a leading `r#` raw-identifier prefix.
fn ident_from(name: &str) -> Ident {
    match name.strip_prefix("r#") {
        Some(bare) => Ident::new_raw(bare, Span::call_site()),
        None => Ident::new(name, Span::call_site()),
    }
}

fn cardinality_label(cardinality: Cardinality) -> &'static str {
    match cardinality {
        Cardinality::One => ":one",
        Cardinality::Many => ":many",
        Cardinality::Exec => ":exec",
        Cardinality::Batch => ":batch",
    }
}

fn format_tokens(tokens: TokenStream) -> String {
    match syn::parse2::<syn::File>(tokens.clone()) {
        Ok(file) => prettyplease::unparse(&file),
        Err(_) => tokens.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::codegen::queries::describe::{ParamBinding, QueryParam, QueryResult, ResultColumn};
    use crate::codegen::queries::parse::{Cardinality, QuerySpec};
    use crate::schema::{DataType, SqlDialect};
    use crate::snapshots::Snapshot;

    fn described(cardinality: Cardinality, params: Vec<QueryParam>) -> DescribedQuery {
        DescribedQuery {
            spec: QuerySpec {
                name: "q".to_string(),
                cardinality,
                keyset: Vec::new(),
                transaction: false,
                sql: "SELECT n FROM t".to_string(),
                source_file: PathBuf::from("q.sql"),
            },
            sql: "SELECT n FROM t".to_string(),
            params,
            result: QueryResult::Row {
                columns: vec![ResultColumn {
                    name: "n".to_string(),
                    data_type: DataType::Integer,
                    nullable: false,
                }],
            },
        }
    }

    fn render(queries: &[DescribedQuery]) -> String {
        generate_rust_module(
            queries,
            &Snapshot::new(SqlDialect::Postgres),
            &CodegenConfig::default(),
            None,
        )
    }

    #[test]
    fn omits_pagination_types_when_no_query_needs_them() {
        let out = render(&[described(Cardinality::One, vec![])]);
        assert!(!out.contains("struct Pagination"));
        assert!(!out.contains("struct Page"));
        assert!(!out.contains("CursorPagination"));
    }

    #[test]
    fn emits_only_limit_offset_types_for_limit_offset_batch() {
        let out = render(&[described(
            Cardinality::Batch,
            vec![
                QueryParam {
                    data_type: DataType::BigInt,
                    binding: ParamBinding::PageLimit,
                },
                QueryParam {
                    data_type: DataType::BigInt,
                    binding: ParamBinding::PageOffset,
                },
            ],
        )]);
        assert!(out.contains("pub struct Pagination"));
        assert!(out.contains("pub struct Page<T>"));
        // A limit/offset batch does not pull in the keyset cursor type.
        assert!(!out.contains("CursorPagination"));
    }

    #[test]
    fn emits_cursor_type_and_tuple_key_for_keyset_batch() {
        let out = render(&[described(
            Cardinality::Batch,
            vec![
                QueryParam {
                    data_type: DataType::Integer,
                    binding: ParamBinding::Cursor {
                        key_index: 0,
                        field: "id".to_string(),
                    },
                },
                QueryParam {
                    data_type: DataType::Text,
                    binding: ParamBinding::Cursor {
                        key_index: 1,
                        field: "email".to_string(),
                    },
                },
                // page size
                QueryParam {
                    data_type: DataType::BigInt,
                    binding: ParamBinding::Arg(None),
                },
            ],
        )]);
        assert!(out.contains("pub struct CursorPagination"));
        // Two keyset keys -> a tuple cursor key, bound by tuple field.
        assert!(out.contains("cursor: &CursorPagination<(i32, String)>"));
        assert!(out.contains("cursor.key.0"));
        assert!(out.contains("cursor.key.1"));
        assert!(out.contains("sqlx::Result<KeysetPage<QRow, (i32, String)>>"));
        assert!(out.contains("CursorPagination::new((row.id.clone(), row.email.clone()))"));
        assert!(!out.contains("struct Pagination"));
    }

    #[test]
    fn single_keyset_key_binds_cursor_key_directly() {
        let out = render(&[described(
            Cardinality::Batch,
            vec![
                QueryParam {
                    data_type: DataType::Integer,
                    binding: ParamBinding::Cursor {
                        key_index: 0,
                        field: "n".to_string(),
                    },
                },
                QueryParam {
                    data_type: DataType::BigInt,
                    binding: ParamBinding::Arg(None),
                },
            ],
        )]);
        assert!(out.contains("cursor: &CursorPagination<i32>"));
        assert!(out.contains(".bind(cursor.key.clone())"));
        assert!(out.contains("CursorPagination::new(row.n.clone())"));
        assert!(!out.contains("cursor.key.0"));
    }
}
