use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use heck::ToSnakeCase;

use crate::Result;
use crate::commands::codegen::CodegenConfig;
use crate::commands::codegen::writer::CodeWriter;

use super::{GeneratedRust, RustStruct};

// ============================================================================
// Rust Writer
// ============================================================================

/// Writer for Rust code generation
pub struct RustWriter;

impl RustWriter {
    const HEADER: &'static str = "//! Generated by shki - DO NOT EDIT";

    /// Write header to a file
    fn write_header(file: &mut fs::File) -> Result<()> {
        writeln!(file, "{}", Self::HEADER)?;
        writeln!(file)?;
        Ok(())
    }

    /// Write imports to a file
    fn write_imports(file: &mut fs::File, imports: &[String]) -> Result<()> {
        if !imports.is_empty() {
            for import in imports {
                writeln!(file, "{}", import)?;
            }
            writeln!(file)?;
        }
        Ok(())
    }

    /// Write mod.rs file for module modes
    fn write_mod_file(mod_path: &Path, mod_entries: &[(String, String)]) -> Result<()> {
        let mut mod_file = fs::File::create(mod_path)?;

        writeln!(mod_file, "{}", Self::HEADER)?;
        writeln!(mod_file)?;

        // Write mod declarations
        for (module_name, _) in mod_entries {
            writeln!(mod_file, "mod {};", module_name)?;
        }
        writeln!(mod_file)?;

        // Write pub use statements
        for (module_name, type_name) in mod_entries {
            writeln!(mod_file, "pub use {}::{};", module_name, type_name)?;
        }

        Ok(())
    }

    /// Collect imports needed for a struct
    fn collect_struct_imports(rust_struct: &RustStruct, code: &GeneratedRust) -> Vec<String> {
        let mut imports = Vec::new();

        for field in &rust_struct.fields {
            // Check if the field type is a known enum
            for rust_enum in code.enums.values() {
                if field.rust_type.contains(&rust_enum.name) {
                    let module_name = rust_enum.name.to_snake_case();
                    imports.push(format!("use super::{}::{};", module_name, rust_enum.name));
                }
            }

            // Standard library imports
            if field.rust_type.contains("chrono::") {
                imports.push("use chrono;".to_string());
            }
            if field.rust_type.contains("uuid::") {
                imports.push("use uuid;".to_string());
            }
            if field.rust_type.contains("serde_json::") {
                imports.push("use serde_json;".to_string());
            }
        }

        imports.sort();
        imports.dedup();
        imports
    }

    /// Create the module directory structure for Modules mode
    fn ensure_module_structure(
        module_dir: &Path,
        module_name: &str,
        type_name: &str,
        impl_name: &str,
    ) -> Result<()> {
        fs::create_dir_all(module_dir)?;

        let module_path = module_dir.join("mod.rs");
        if !module_path.exists() {
            let mut file = fs::File::create(&module_path)?;
            writeln!(file, "{}", Self::HEADER)?;
            writeln!(file, "\npub mod {};", module_name)?;
            writeln!(file, "pub use {}::*;", module_name)?;
            writeln!(file, "pub mod {};", impl_name)?;
            writeln!(file, "pub use {}::*;", impl_name)?;
        }

        let impl_path = module_dir.join(format!("{}.rs", impl_name));
        if !impl_path.exists() {
            let mut file = fs::File::create(&impl_path)?;
            writeln!(file, "//! Implementation details for {}", type_name)?;
        }

        Ok(())
    }
}

impl CodeWriter for RustWriter {
    type GeneratedCode = GeneratedRust;

    fn write_single_file(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        fs::create_dir_all(output_dir)?;

        let file_path = output_dir.join(format!(
            "{}.{}",
            self.default_filename(),
            self.file_extension()
        ));
        let mut file = fs::File::create(&file_path)?;

        Self::write_header(&mut file)?;
        Self::write_imports(&mut file, &code.required_imports())?;

        // Write enums first, then structs
        for rust_enum in code.enums.values() {
            writeln!(file, "{}", rust_enum.to_string_pretty())?;
        }
        for rust_struct in code.structs.values() {
            writeln!(file, "{}", rust_struct.to_string_pretty())?;
        }

        Ok(vec![file_path])
    }

    fn write_single_module(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        fs::create_dir_all(output_dir)?;

        let mut written_files = Vec::new();
        let mut mod_entries: Vec<(String, String)> = Vec::new();

        // Write enum files
        for rust_enum in code.enums.values() {
            let module_name = rust_enum.name.to_snake_case();
            let file_path = output_dir.join(format!("{}.{}", module_name, self.file_extension()));

            let mut file = fs::File::create(&file_path)?;
            Self::write_header(&mut file)?;
            writeln!(file, "{}", rust_enum.to_string_pretty())?;

            written_files.push(file_path);
            mod_entries.push((module_name, rust_enum.name.clone()));
        }

        // Write struct files
        for rust_struct in code.structs.values() {
            let module_name = rust_struct.name.to_snake_case();
            let file_path = output_dir.join(format!("{}.{}", module_name, self.file_extension()));
            let imports = Self::collect_struct_imports(rust_struct, code);

            let mut file = fs::File::create(&file_path)?;
            Self::write_header(&mut file)?;
            Self::write_imports(&mut file, &imports)?;
            writeln!(file, "{}", rust_struct.to_string_pretty())?;

            written_files.push(file_path);
            mod_entries.push((module_name, rust_struct.name.clone()));
        }

        // Write mod.rs
        let mod_path = output_dir.join("mod.rs");
        Self::write_mod_file(&mod_path, &mod_entries)?;
        written_files.push(mod_path);

        Ok(written_files)
    }

    fn write_modules(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        fs::create_dir_all(output_dir)?;

        /// Information about a type to be written
        struct TypeModuleInfo {
            module_name: String,
            type_name: String,
            imports: Vec<String>,
            content: String,
        }

        // Collect all types to write
        let types: Vec<TypeModuleInfo> = code
            .enums
            .values()
            .map(|e| TypeModuleInfo {
                module_name: e.name.to_snake_case(),
                type_name: e.name.clone(),
                imports: vec![],
                content: e.to_string_pretty(),
            })
            .chain(code.structs.values().map(|s| TypeModuleInfo {
                module_name: s.name.to_snake_case(),
                type_name: s.name.clone(),
                imports: Self::collect_struct_imports(s, code),
                content: s.to_string_pretty(),
            }))
            .collect();

        let mut written_files = Vec::new();

        for type_info in &types {
            let impl_name = config
                .impl_file_name
                .clone()
                .unwrap_or_else(|| format!("impl_{}", type_info.module_name));

            let module_dir = output_dir.join(&type_info.module_name);

            Self::ensure_module_structure(
                &module_dir,
                &type_info.module_name,
                &type_info.type_name,
                &impl_name,
            )?;

            // Write the type file
            let file_path = module_dir.join(format!(
                "{}.{}",
                type_info.module_name,
                self.file_extension()
            ));
            let mut file = fs::File::create(&file_path)?;
            Self::write_header(&mut file)?;
            Self::write_imports(&mut file, &type_info.imports)?;
            writeln!(file, "{}", type_info.content)?;

            written_files.push(file_path);
        }

        let mod_defs = types
            .into_iter()
            .map(|t| (t.module_name, t.type_name))
            .collect::<Vec<_>>();

        Self::write_mod_file(output_dir.join("mod.rs").as_path(), &mod_defs)?;

        Ok(written_files)
    }

    fn format_preview(&self, code: &Self::GeneratedCode) -> String {
        let mut output = String::new();

        output.push_str("//! Generated by shki\n\n");

        // Imports
        let imports = code.required_imports();
        if !imports.is_empty() {
            for import in imports {
                output.push_str(&import);
                output.push('\n');
            }
            output.push('\n');
        }

        // Enums
        for rust_enum in code.enums.values() {
            output.push_str(&rust_enum.to_string_pretty());
            output.push('\n');
        }

        // Structs
        for rust_struct in code.structs.values() {
            output.push_str(&rust_struct.to_string_pretty());
            output.push('\n');
        }

        output
    }

    fn file_extension(&self) -> &str {
        "rs"
    }

    fn default_filename(&self) -> &str {
        "models"
    }
}
