//! File writing utilities for generated code

use crate::{Result, ShkiError};
use heck::ToSnakeCase;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use super::{CodegenConfig, GeneratedCode, OutputMode};

const GENERATED_HEADER: &str = "//! Generated by shki - DO NOT EDIT";

/// A type that can be written to a generated file
trait GeneratedType {
    fn to_string_pretty(&self) -> String;
}

impl GeneratedType for super::RustEnum {
    fn to_string_pretty(&self) -> String {
        self.to_string_pretty()
    }
}

impl GeneratedType for super::RustStruct {
    fn to_string_pretty(&self) -> String {
        self.to_string_pretty()
    }
}

/// Write generated code to files
pub fn write_generated_code(code: &GeneratedCode, config: &CodegenConfig) -> Result<Vec<PathBuf>> {
    let output_dir = config
        .output
        .as_ref()
        .ok_or_else(|| ShkiError::Config("No output directory specified".to_string()))?;

    match config.mode {
        OutputMode::SingleFile => write_single_file(code, output_dir),
        OutputMode::SingleModule => write_single_module(code, output_dir),
        OutputMode::Modules => write_modules(code, output_dir, config),
    }
}

/// Write the standard generated file header
fn write_header(file: &mut fs::File) -> Result<()> {
    writeln!(file, "{}", GENERATED_HEADER)?;
    writeln!(file)?;
    Ok(())
}

/// Write imports to a file
fn write_imports(file: &mut fs::File, imports: &[String]) -> Result<()> {
    if !imports.is_empty() {
        for import in imports {
            writeln!(file, "{}", import)?;
        }
        writeln!(file)?;
    }
    Ok(())
}

/// Write all code to a single file
fn write_single_file(code: &GeneratedCode, output_dir: &Path) -> Result<Vec<PathBuf>> {
    fs::create_dir_all(output_dir)?;

    let file_path = output_dir.join("models.rs");
    let mut file = fs::File::create(&file_path)?;

    write_header(&mut file)?;
    write_imports(&mut file, &code.required_imports())?;

    // Write enums first, then structs
    for rust_enum in code.enums.values() {
        writeln!(file, "{}", rust_enum.to_string_pretty())?;
    }
    for rust_struct in code.structs.values() {
        writeln!(file, "{}", rust_struct.to_string_pretty())?;
    }

    Ok(vec![file_path])
}

/// Write a single type to a file with header and optional imports
fn write_type_file<T: GeneratedType>(
    file_path: &Path,
    generated_type: &T,
    imports: &[String],
) -> Result<()> {
    let mut file = fs::File::create(file_path)?;
    write_header(&mut file)?;
    write_imports(&mut file, imports)?;
    writeln!(file, "{}", generated_type.to_string_pretty())?;
    Ok(())
}

/// Write the mod.rs file for SingleModule mode
fn write_mod_file(mod_path: &Path, mod_entries: &[(String, String)]) -> Result<()> {
    let mut mod_file = fs::File::create(mod_path)?;

    writeln!(mod_file, "{}", GENERATED_HEADER)?;
    writeln!(mod_file)?;

    // Write mod declarations
    for (module_name, _) in mod_entries {
        writeln!(mod_file, "mod {};", module_name)?;
    }
    writeln!(mod_file)?;

    // Write pub use statements
    for (module_name, type_name) in mod_entries {
        writeln!(mod_file, "pub use {}::{};", module_name, type_name)?;
    }

    Ok(())
}

/// Write code to a module directory with separate files (flat structure)
fn write_single_module(code: &GeneratedCode, output_dir: &Path) -> Result<Vec<PathBuf>> {
    fs::create_dir_all(output_dir)?;

    let mut written_files = Vec::new();
    let mut mod_entries: Vec<(String, String)> = Vec::new();

    // Write enum files
    for rust_enum in code.enums.values() {
        let module_name = rust_enum.name.to_snake_case();
        let file_path = output_dir.join(format!("{}.rs", module_name));

        write_type_file(&file_path, rust_enum, &[])?;

        written_files.push(file_path);
        mod_entries.push((module_name, rust_enum.name.clone()));
    }

    // Write struct files
    for rust_struct in code.structs.values() {
        let module_name = rust_struct.name.to_snake_case();
        let file_path = output_dir.join(format!("{}.rs", module_name));
        let imports = collect_struct_imports(rust_struct, code);

        write_type_file(&file_path, rust_struct, &imports)?;

        written_files.push(file_path);
        mod_entries.push((module_name, rust_struct.name.clone()));
    }

    // Write mod.rs
    let mod_path = output_dir.join("mod.rs");
    write_mod_file(&mod_path, &mod_entries)?;
    written_files.push(mod_path);

    Ok(written_files)
}

/// Information about a type to be written in Modules mode
struct TypeModuleInfo {
    module_name: String,
    type_name: String,
    imports: Vec<String>,
    content: String,
}

/// Create the module directory structure (mod.rs and impl file) if it doesn't exist
fn ensure_module_structure(
    module_dir: &Path,
    module_name: &str,
    type_name: &str,
    impl_name: &str,
) -> Result<()> {
    fs::create_dir_all(module_dir)?;

    let module_path = module_dir.join("mod.rs");
    if !module_path.exists() {
        let mut file = fs::File::create(&module_path)?;
        writeln!(file, "{}", GENERATED_HEADER)?;
        writeln!(file, "\npub mod {};", module_name)?;
        writeln!(file, "pub use {}::*;", module_name)?;
        writeln!(file, "pub mod {};", impl_name)?;
        writeln!(file, "pub use {}::*;", impl_name)?;
    }

    let impl_path = module_dir.join(format!("{}.rs", impl_name));
    if !impl_path.exists() {
        let mut file = fs::File::create(&impl_path)?;
        writeln!(file, "//! Implementation details for {}", type_name)?;
    }

    Ok(())
}

/// Write code to a module directory with nested module structure
fn write_modules(
    code: &GeneratedCode,
    output_dir: &Path,
    config: &CodegenConfig,
) -> Result<Vec<PathBuf>> {
    fs::create_dir_all(output_dir)?;

    // Collect all types to write
    let types: Vec<TypeModuleInfo> = code
        .enums
        .values()
        .map(|e| TypeModuleInfo {
            module_name: e.name.to_snake_case(),
            type_name: e.name.clone(),
            imports: vec![],
            content: e.to_string_pretty(),
        })
        .chain(code.structs.values().map(|s| TypeModuleInfo {
            module_name: s.name.to_snake_case(),
            type_name: s.name.clone(),
            imports: collect_struct_imports(s, code),
            content: s.to_string_pretty(),
        }))
        .collect();

    let mut written_files = Vec::new();

    for type_info in &types {
        let impl_name = config
            .impl_file_name
            .clone()
            .unwrap_or_else(|| format!("impl_{}", type_info.module_name));

        let module_dir = output_dir.join(&type_info.module_name);

        ensure_module_structure(
            &module_dir,
            &type_info.module_name,
            &type_info.type_name,
            &impl_name,
        )?;

        // Write the type file
        let file_path = module_dir.join(format!("{}.rs", type_info.module_name));
        let mut file = fs::File::create(&file_path)?;
        write_header(&mut file)?;
        write_imports(&mut file, &type_info.imports)?;
        writeln!(file, "{}", type_info.content)?;

        written_files.push(file_path);
    }

    let mod_defs = types
        .into_iter()
        .map(|t| (t.module_name, t.type_name))
        .collect::<Vec<_>>();

    write_mod_file(output_dir.join("mod.rs").as_path(), &mod_defs)?;

    Ok(written_files)
}

/// Collect imports needed for a struct (e.g., enum types from other modules)
fn collect_struct_imports(rust_struct: &super::RustStruct, code: &GeneratedCode) -> Vec<String> {
    let mut imports = Vec::new();

    for field in &rust_struct.fields {
        // Check if the field type is a known enum
        for rust_enum in code.enums.values() {
            if field.rust_type.contains(&rust_enum.name) {
                let module_name = rust_enum.name.to_snake_case();
                imports.push(format!("use super::{}::{};", module_name, rust_enum.name));
            }
        }

        // Standard library imports
        if field.rust_type.contains("chrono::") {
            imports.push("use chrono;".to_string());
        }
        if field.rust_type.contains("uuid::") {
            imports.push("use uuid;".to_string());
        }
        if field.rust_type.contains("serde_json::") {
            imports.push("use serde_json;".to_string());
        }
    }

    imports.sort();
    imports.dedup();
    imports
}

/// Format generated code as a string (for preview/stdout)
pub fn format_generated_code(code: &GeneratedCode) -> String {
    let mut output = String::new();

    output.push_str("//! Generated by shki\n\n");

    // Imports
    let imports = code.required_imports();
    if !imports.is_empty() {
        for import in imports {
            output.push_str(&import);
            output.push('\n');
        }
        output.push('\n');
    }

    // Enums
    for rust_enum in code.enums.values() {
        output.push_str(&rust_enum.to_string_pretty());
        output.push('\n');
    }

    // Structs
    for rust_struct in code.structs.values() {
        output.push_str(&rust_struct.to_string_pretty());
        output.push('\n');
    }

    output
}
