//! File writing utilities for generated code

use crate::{Result, ShkiError};
use heck::ToSnakeCase;
use std::fs;
use std::io::Write;
use std::path::Path;

use super::{CodegenConfig, GeneratedCode, OutputMode};

/// Write generated code to files
pub fn write_generated_code(
    code: &GeneratedCode,
    config: &CodegenConfig,
) -> Result<Vec<std::path::PathBuf>> {
    let output_dir = config
        .output_dir
        .as_ref()
        .ok_or_else(|| ShkiError::Config("No output directory specified".to_string()))?;

    match config.output_mode {
        OutputMode::SingleFile => write_single_file(code, output_dir),
        OutputMode::Module => write_module(code, output_dir, config),
    }
}

/// Write all code to a single file
fn write_single_file(code: &GeneratedCode, output_dir: &Path) -> Result<Vec<std::path::PathBuf>> {
    fs::create_dir_all(output_dir)?;

    let file_path = output_dir.join("models.rs");
    let mut file = fs::File::create(&file_path)?;

    // Write header
    writeln!(file, "//! Generated by shki - DO NOT EDIT")?;
    writeln!(file)?;

    // Write imports
    let imports = code.required_imports();
    if !imports.is_empty() {
        for import in imports {
            writeln!(file, "{}", import)?;
        }
        writeln!(file)?;
    }

    // Write enums first
    for rust_enum in code.enums.values() {
        writeln!(file, "{}", rust_enum.to_string_pretty())?;
    }

    // Write structs
    for rust_struct in code.structs.values() {
        writeln!(file, "{}", rust_struct.to_string_pretty())?;
    }

    Ok(vec![file_path])
}

/// Write code to a module directory with separate files
fn write_module(
    code: &GeneratedCode,
    output_dir: &Path,
    config: &CodegenConfig,
) -> Result<Vec<std::path::PathBuf>> {
    fs::create_dir_all(output_dir)?;

    let mut written_files = Vec::new();
    let mut mod_entries: Vec<(String, String)> = Vec::new(); // (module_name, type_name)

    // Write enum files
    for rust_enum in code.enums.values() {
        let module_name = rust_enum.name.to_snake_case();
        let file_path = output_dir.join(format!("{}.rs", module_name));

        let mut file = fs::File::create(&file_path)?;
        writeln!(file, "//! Generated by shki - DO NOT EDIT")?;
        writeln!(file)?;
        writeln!(file, "{}", rust_enum.to_string_pretty())?;

        written_files.push(file_path);
        mod_entries.push((module_name, rust_enum.name.clone()));
    }

    // Write struct files
    for rust_struct in code.structs.values() {
        let module_name = rust_struct.name.to_snake_case();
        let file_path = output_dir.join(format!("{}.rs", module_name));

        let mut file = fs::File::create(&file_path)?;
        writeln!(file, "//! Generated by shki - DO NOT EDIT")?;
        writeln!(file)?;

        // Add imports for enum types used by this struct
        let imports = collect_struct_imports(rust_struct, code);
        for import in &imports {
            writeln!(file, "{}", import)?;
        }
        if !imports.is_empty() {
            writeln!(file)?;
        }

        writeln!(file, "{}", rust_struct.to_string_pretty())?;

        written_files.push(file_path);
        mod_entries.push((module_name, rust_struct.name.clone()));
    }

    // Write mod.rs if configured
    if config.generate_mod_file {
        let mod_path = output_dir.join("mod.rs");
        let mut mod_file = fs::File::create(&mod_path)?;

        writeln!(mod_file, "//! Generated by shki - DO NOT EDIT")?;
        writeln!(mod_file)?;

        // Write mod declarations
        for (module_name, _) in &mod_entries {
            writeln!(mod_file, "mod {};", module_name)?;
        }

        writeln!(mod_file)?;

        // Write pub use statements
        for (module_name, type_name) in &mod_entries {
            writeln!(mod_file, "pub use {}::{};", module_name, type_name)?;
        }

        written_files.push(mod_path);
    }

    Ok(written_files)
}

/// Collect imports needed for a struct (e.g., enum types from other modules)
fn collect_struct_imports(rust_struct: &super::RustStruct, code: &GeneratedCode) -> Vec<String> {
    let mut imports = Vec::new();

    for field in &rust_struct.fields {
        // Check if the field type is a known enum
        for rust_enum in code.enums.values() {
            if field.rust_type.contains(&rust_enum.name) {
                let module_name = rust_enum.name.to_snake_case();
                imports.push(format!("use super::{}::{};", module_name, rust_enum.name));
            }
        }

        // Standard library imports
        if field.rust_type.contains("chrono::") {
            imports.push("use chrono;".to_string());
        }
        if field.rust_type.contains("uuid::") {
            imports.push("use uuid;".to_string());
        }
        if field.rust_type.contains("serde_json::") {
            imports.push("use serde_json;".to_string());
        }
    }

    imports.sort();
    imports.dedup();
    imports
}

/// Format generated code as a string (for preview/stdout)
pub fn format_generated_code(code: &GeneratedCode) -> String {
    let mut output = String::new();

    output.push_str("//! Generated by shki\n\n");

    // Imports
    let imports = code.required_imports();
    if !imports.is_empty() {
        for import in imports {
            output.push_str(&import);
            output.push('\n');
        }
        output.push('\n');
    }

    // Enums
    for rust_enum in code.enums.values() {
        output.push_str(&rust_enum.to_string_pretty());
        output.push('\n');
    }

    // Structs
    for rust_struct in code.structs.values() {
        output.push_str(&rust_struct.to_string_pretty());
        output.push('\n');
    }

    output
}
