//! TypeScript file writer
//!
//! Writes generated TypeScript code to files in various output modes.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use colored::Colorize;
use heck::ToSnakeCase;

use crate::Result;
use crate::commands::codegen::CodegenConfig;
use crate::commands::codegen::writer::CodeWriter;

use super::{GeneratedTypeScript, TypeScriptInterface, TypescriptFlavor};

// ============================================================================
// TypeScript Writer
// ============================================================================

/// Writer for TypeScript code generation
#[derive(Default)]
pub struct TypeScriptWriter {
    pub flavor: TypescriptFlavor,
}

impl TypeScriptWriter {
    const HEADER: &'static str = "// Generated by shki - DO NOT EDIT";

    pub fn new(flavor: TypescriptFlavor) -> Self {
        Self { flavor }
    }

    /// Write header to a file
    fn write_header(&self, file: &mut fs::File) -> Result<()> {
        writeln!(file, "{}", Self::HEADER)?;
        writeln!(file)?;
        Ok(())
    }

    /// Collect enum imports needed for an interface
    fn collect_interface_imports(
        &self,
        ts_interface: &TypeScriptInterface,
        code: &GeneratedTypeScript,
    ) -> Vec<String> {
        let mut imports = Vec::new();

        for property in &ts_interface.properties {
            // Check if the property type is a known enum
            for ts_enum in code.enums.values() {
                if property.ts_type.contains(&ts_enum.name) {
                    let module_name = ts_enum.name.to_snake_case();
                    match self.flavor {
                        TypescriptFlavor::Type => imports.push(format!(
                            "import type {{ {} }} from './{}';",
                            ts_enum.name, module_name
                        )),
                        TypescriptFlavor::Interface => imports.push(format!(
                            "import {{ {} }} from './{}';",
                            ts_enum.name, module_name
                        )),
                    };
                }
            }
        }

        imports.sort();
        imports.dedup();
        imports
    }

    /// Write imports to a file
    fn write_imports(&self, file: &mut fs::File, imports: &[String]) -> Result<()> {
        if !imports.is_empty() {
            for import in imports {
                writeln!(file, "{}", import)?;
            }
            writeln!(file)?;
        }
        Ok(())
    }

    fn write_type_file(&self, file_path: &Path, imports: &[String], content: &str) -> Result<()> {
        let mut file = fs::File::create(file_path)?;
        self.write_header(&mut file)?;
        self.write_imports(&mut file, imports)?;
        writeln!(file, "{}", content)?;
        Ok(())
    }

    /// Write an index.ts file that re-exports all types
    fn write_index_file(&self, index_path: &Path, exports: &[ExportEntry]) -> Result<()> {
        let mut file = fs::File::create(index_path)?;

        writeln!(file, "{}", Self::HEADER)?;
        writeln!(file)?;

        for export in exports {
            writeln!(
                file,
                "export {{ {} }} from './{}';",
                export.type_name, export.module_name
            )?;
        }

        Ok(())
    }

    fn collect_generated_items(&self, code: &GeneratedTypeScript) -> Vec<GeneratedItem> {
        code.enums
            .values()
            .map(|e| {
                GeneratedItem::new(
                    e.name.to_snake_case(),
                    e.name.clone(),
                    vec![],
                    e.to_string(),
                )
            })
            .chain(code.interfaces.values().map(|i| {
                GeneratedItem::new(
                    i.name.to_snake_case(),
                    i.name.clone(),
                    self.collect_interface_imports(i, code),
                    i.to_string(),
                )
            }))
            .collect()
    }
}

struct ExportEntry {
    module_name: String,
    type_name: String,
}

impl ExportEntry {
    fn new(module_name: impl Into<String>, type_name: impl Into<String>) -> Self {
        Self {
            module_name: module_name.into(),
            type_name: type_name.into(),
        }
    }
}

struct GeneratedItem {
    module_name: String,
    type_name: String,
    imports: Vec<String>,
    content: String,
}

impl GeneratedItem {
    fn new(
        module_name: impl Into<String>,
        type_name: impl Into<String>,
        imports: Vec<String>,
        content: String,
    ) -> Self {
        Self {
            module_name: module_name.into(),
            type_name: type_name.into(),
            imports,
            content,
        }
    }
}

impl CodeWriter for TypeScriptWriter {
    type GeneratedCode = GeneratedTypeScript;

    fn write_single_file(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let file_path = self.output_file_path(output_dir);
        let mut file = fs::File::create(&file_path)?;

        self.write_header(&mut file)?;

        for item in self.collect_generated_items(code) {
            writeln!(file, "{}", item.content)?;
        }

        println!("Generated TypeScript types: {}", file_path.display());

        Ok(vec![file_path])
    }

    fn write_single_module(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let items = self.collect_generated_items(code);
        let mut written_files = Vec::new();
        let mut exports = Vec::new();

        for item in &items {
            let file_path =
                output_dir.join(format!("{}.{}", item.module_name, self.file_extension()));
            self.write_type_file(&file_path, &item.imports, &item.content)?;
            written_files.push(file_path);
            exports.push(ExportEntry::new(&item.module_name, &item.type_name));
        }

        // Write index.ts
        let index_path = output_dir.join("index.ts");
        self.write_index_file(&index_path, &exports)?;
        written_files.push(index_path);

        println!(
            "Generated {} TypeScript files in {}",
            written_files.len(),
            output_dir.display()
        );

        Ok(written_files)
    }

    fn write_modules(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        println!("-");
        println!(
            "{}: Typescript codegen doesn't currently support {} setting",
            "Warning".yellow().bold(),
            "modules".cyan()
        );
        println!("Falling back to {}", "single-module".cyan().bold());
        println!("-");

        // For TypeScript, modules mode is the same as single_module
        // (separate files with an index.ts barrel file)
        self.write_single_module(code, output_dir, config)
    }

    fn format_preview(&self, code: &Self::GeneratedCode) -> String {
        let mut output = String::new();

        output.push_str(Self::HEADER);
        output.push_str("\n\n");

        for item in self.collect_generated_items(code) {
            output.push_str(&item.content);
            output.push('\n');
        }

        output
    }

    fn file_extension(&self) -> &str {
        "ts"
    }

    fn default_filename(&self) -> &str {
        "models"
    }
}
