//! TypeScript file writer
//!
//! Writes generated TypeScript code to files in various output modes.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use colored::Colorize;
use heck::ToSnakeCase;

use crate::Result;
use crate::commands::codegen::CodegenConfig;
use crate::commands::codegen::writer::CodeWriter;

use super::{GeneratedTypeScript, TypeScriptInterface};

// ============================================================================
// TypeScript Writer
// ============================================================================

/// Writer for TypeScript code generation
pub struct TypeScriptWriter;

impl TypeScriptWriter {
    const HEADER: &'static str = "// Generated by shki - DO NOT EDIT";

    /// Write header to a file
    fn write_header(file: &mut fs::File) -> Result<()> {
        writeln!(file, "{}", Self::HEADER)?;
        writeln!(file)?;
        Ok(())
    }

    /// Collect enum imports needed for an interface
    fn collect_interface_imports(
        ts_interface: &TypeScriptInterface,
        code: &GeneratedTypeScript,
    ) -> Vec<String> {
        let mut imports = Vec::new();

        for property in &ts_interface.properties {
            // Check if the property type is a known enum
            for ts_enum in code.enums.values() {
                if property.ts_type.contains(&ts_enum.name) {
                    let module_name = ts_enum.name.to_snake_case();
                    imports.push(format!(
                        "import {{ {} }} from './{}';",
                        ts_enum.name, module_name
                    ));
                }
            }
        }

        imports.sort();
        imports.dedup();
        imports
    }

    /// Write imports to a file
    fn write_imports(file: &mut fs::File, imports: &[String]) -> Result<()> {
        if !imports.is_empty() {
            for import in imports {
                writeln!(file, "{}", import)?;
            }
            writeln!(file)?;
        }
        Ok(())
    }

    /// Write an index.ts file that re-exports all types
    fn write_index_file(index_path: &Path, exports: &[(String, String)]) -> Result<()> {
        let mut file = fs::File::create(index_path)?;

        writeln!(file, "{}", Self::HEADER)?;
        writeln!(file)?;

        for (module_name, type_name) in exports {
            writeln!(file, "export {{ {} }} from './{}';", type_name, module_name)?;
        }

        Ok(())
    }
}

impl CodeWriter for TypeScriptWriter {
    type GeneratedCode = GeneratedTypeScript;

    fn write_single_file(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        fs::create_dir_all(output_dir)?;

        let file_path = output_dir.join(format!(
            "{}.{}",
            self.default_filename(),
            self.file_extension()
        ));
        let mut file = fs::File::create(&file_path)?;

        Self::write_header(&mut file)?;

        // Write enums first, then interfaces
        for ts_enum in code.enums.values() {
            writeln!(file, "{}", ts_enum)?;
        }
        for ts_interface in code.interfaces.values() {
            writeln!(file, "{}", ts_interface)?;
        }

        println!("Generated TypeScript types: {}", file_path.display());

        Ok(vec![file_path])
    }

    fn write_single_module(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        fs::create_dir_all(output_dir)?;

        let mut written_files = Vec::new();
        let mut exports: Vec<(String, String)> = Vec::new();

        // Write enum files
        for ts_enum in code.enums.values() {
            let module_name = ts_enum.name.to_snake_case();
            let file_path = output_dir.join(format!("{}.{}", module_name, self.file_extension()));

            let mut file = fs::File::create(&file_path)?;
            Self::write_header(&mut file)?;
            writeln!(file, "{}", ts_enum)?;

            written_files.push(file_path);
            exports.push((module_name, ts_enum.name.clone()));
        }

        // Write interface files
        for ts_interface in code.interfaces.values() {
            let module_name = ts_interface.name.to_snake_case();
            let file_path = output_dir.join(format!("{}.{}", module_name, self.file_extension()));
            let imports = Self::collect_interface_imports(ts_interface, code);

            let mut file = fs::File::create(&file_path)?;
            Self::write_header(&mut file)?;
            Self::write_imports(&mut file, &imports)?;
            writeln!(file, "{}", ts_interface)?;

            written_files.push(file_path);
            exports.push((module_name, ts_interface.name.clone()));
        }

        // Write index.ts
        let index_path = output_dir.join("index.ts");
        Self::write_index_file(&index_path, &exports)?;
        written_files.push(index_path);

        println!(
            "Generated {} TypeScript files in {}",
            written_files.len(),
            output_dir.display()
        );

        Ok(written_files)
    }

    fn write_modules(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        println!();
        println!("-");
        println!(
            "{}: Typescript codegen doesn't currently support {} setting",
            "Warning".yellow().bold(),
            "modules".cyan()
        );
        println!("Falling back to {}", "single-module".cyan().bold());
        println!("-");
        println!();

        // For TypeScript, modules mode is the same as single_module
        // (separate files with an index.ts barrel file)
        self.write_single_module(code, output_dir, config)
    }

    fn format_preview(&self, code: &Self::GeneratedCode) -> String {
        let mut output = String::new();

        output.push_str(Self::HEADER);
        output.push_str("\n\n");

        // Enums
        for ts_enum in code.enums.values() {
            output.push_str(&ts_enum.to_string());
            output.push('\n');
        }

        // Interfaces
        for ts_interface in code.interfaces.values() {
            output.push_str(&ts_interface.to_string());
            output.push('\n');
        }

        output
    }

    fn file_extension(&self) -> &str {
        "ts"
    }

    fn default_filename(&self) -> &str {
        "models"
    }
}
