use std::fmt::Write as _;
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use heck::ToSnakeCase;

use crate::Result;
use crate::codegen::writer::CodeWriter;
use crate::codegen::{CodegenConfig, OutputMode};
use crate::display::preview::PreviewFile;

use super::{GeneratedProto, ProtoMessage};

/// Writer for Protocol Buffer code generation
pub struct ProtobufWriter;

impl ProtobufWriter {
    const HEADER: &'static str = "// Generated by shki - DO NOT EDIT";

    /// Collect imports needed for a specific message
    fn collect_message_imports(message: &ProtoMessage, proto: &GeneratedProto) -> Vec<String> {
        let mut imports = Vec::new();

        for field in &message.fields {
            if field.proto_type.starts_with("google.protobuf.") {
                let import = match field.proto_type.as_str() {
                    "google.protobuf.Timestamp" => "google/protobuf/timestamp.proto",
                    "google.protobuf.Duration" => "google/protobuf/duration.proto",
                    "google.protobuf.Struct" => "google/protobuf/struct.proto",
                    "google.protobuf.Any" => "google/protobuf/any.proto",
                    _ => continue,
                };
                if !imports.contains(&import.to_string()) {
                    imports.push(import.to_string());
                }
            }

            for proto_enum in proto.enums.values() {
                if field.proto_type == proto_enum.name {
                    let import = format!("{}.proto", proto_enum.name.to_snake_case());
                    if !imports.contains(&import) {
                        imports.push(import);
                    }
                }
            }
        }

        imports.sort();
        imports
    }

    /// Build the contents of a per-type `.proto` file: header, syntax/package
    /// preamble, imports, then the type definition.
    fn format_type_file(
        package: &str,
        imports: &[String],
        content: &impl std::fmt::Display,
    ) -> String {
        let mut output = String::new();

        writeln!(output, "{}", Self::HEADER).expect("writing to string should not fail");
        writeln!(output).expect("writing to string should not fail");
        writeln!(output, "syntax = \"proto3\";\n").expect("writing to string should not fail");
        writeln!(output, "package {};\n", package).expect("writing to string should not fail");

        if !imports.is_empty() {
            for import in imports {
                writeln!(output, "import \"{}\";", import)
                    .expect("writing to string should not fail");
            }
            writeln!(output).expect("writing to string should not fail");
        }

        write!(output, "{}", content).expect("writing to string should not fail");

        output
    }

    /// The per-type files this writer produces in module modes (one file per
    /// enum and message), used for both writing and previewing.
    fn type_files(&self, code: &GeneratedProto) -> Vec<PreviewFile> {
        let ext = self.file_extension();
        let mut files = Vec::new();

        for proto_enum in code.enums.values() {
            files.push(PreviewFile::new(
                format!("{}.{}", proto_enum.name.to_snake_case(), ext),
                Self::format_type_file(&code.package, &[], proto_enum),
            ));
        }

        for proto_message in code.messages.values() {
            let imports = Self::collect_message_imports(proto_message, code);
            files.push(PreviewFile::new(
                format!("{}.{}", proto_message.name.to_snake_case(), ext),
                Self::format_type_file(&code.package, &imports, proto_message),
            ));
        }

        files
    }
}

impl CodeWriter for ProtobufWriter {
    type GeneratedCode = GeneratedProto;

    fn write_single_file(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let file_path = self.output_file_path(output_dir);
        let mut file = fs::File::create(&file_path)?;
        write!(file, "{}", self.single_file_contents(code))?;

        println!(
            "Generated Protocol Buffer definitions: {}",
            file_path.display()
        );

        Ok(vec![file_path])
    }

    fn write_single_module(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let mut written_files = Vec::new();

        for file in self.type_files(code) {
            let file_path = output_dir.join(&file.path);
            let mut handle = fs::File::create(&file_path)?;
            write!(handle, "{}", file.content)?;
            written_files.push(file_path);
        }

        println!(
            "Generated {} Protocol Buffer files in {}",
            written_files.len(),
            output_dir.display()
        );

        Ok(written_files)
    }

    fn single_file_contents(&self, code: &Self::GeneratedCode) -> String {
        format!("{}\n\n{}", Self::HEADER, code)
    }

    fn preview_files(
        &self,
        code: &Self::GeneratedCode,
        config: &CodegenConfig,
    ) -> Vec<PreviewFile> {
        match config.format {
            OutputMode::File => vec![PreviewFile::new(
                format!("{}.{}", self.default_filename(), self.file_extension()),
                self.single_file_contents(code),
            )],
            OutputMode::Module | OutputMode::Modules => self.type_files(code),
        }
    }

    fn syntax_language(&self) -> &str {
        "protobuf"
    }

    fn file_extension(&self) -> &str {
        "proto"
    }

    fn default_filename(&self) -> &str {
        "schema"
    }
}

#[cfg(test)]
mod tests {
    use super::super::ProtobufGenerator;
    use super::*;
    use crate::codegen::generator::CodeGenerator;
    use crate::models::iden::Iden;
    use crate::schema::{Column, DataType, SqlDialect, Table};
    use crate::snapshots::Snapshot;

    fn sample_code() -> GeneratedProto {
        let mut users = Table::new("users");
        users.column(Column::new("id", DataType::Integer).not_null());
        let mut orders = Table::new("orders");
        orders.column(Column::new("id", DataType::Integer).not_null());

        let mut snapshot = Snapshot::new(SqlDialect::Postgres);
        snapshot.insert_table(Iden::new("users", None), users);
        snapshot.insert_table(Iden::new("orders", None), orders);

        ProtobufGenerator::new().generate(&snapshot, &CodegenConfig::default())
    }

    #[test]
    fn preview_file_mode_renders_a_single_labeled_file() {
        let code = sample_code();
        let config = CodegenConfig::default(); // defaults to OutputMode::File
        let preview = ProtobufWriter.format_preview(&code, &config, true);

        assert!(preview.contains("1 file(s):"));
        assert!(preview.contains("schema.proto"));
        assert!(preview.contains("message User"));
        assert!(preview.contains("message Order"));
    }

    #[test]
    fn preview_module_mode_renders_one_file_per_message() {
        let code = sample_code();
        let config = CodegenConfig::default().mode(Some(OutputMode::Module));
        let preview = ProtobufWriter.format_preview(&code, &config, true);

        // Each message lands in its own labeled file, each a full proto file.
        assert!(preview.contains("user.proto"));
        assert!(preview.contains("order.proto"));
        assert_eq!(preview.matches("syntax = \"proto3\";").count(), 2);
    }
}
