use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use heck::ToSnakeCase;

use crate::Result;
use crate::codegen::CodegenConfig;
use crate::codegen::writer::CodeWriter;

use super::{GeneratedProto, ProtoMessage};

/// Writer for Protocol Buffer code generation
pub struct ProtobufWriter;

impl ProtobufWriter {
    const HEADER: &'static str = "// Generated by shki - DO NOT EDIT";

    /// Collect imports needed for a specific message
    fn collect_message_imports(message: &ProtoMessage, proto: &GeneratedProto) -> Vec<String> {
        let mut imports = Vec::new();

        for field in &message.fields {
            if field.proto_type.starts_with("google.protobuf.") {
                let import = match field.proto_type.as_str() {
                    "google.protobuf.Timestamp" => "google/protobuf/timestamp.proto",
                    "google.protobuf.Duration" => "google/protobuf/duration.proto",
                    "google.protobuf.Struct" => "google/protobuf/struct.proto",
                    "google.protobuf.Any" => "google/protobuf/any.proto",
                    _ => continue,
                };
                if !imports.contains(&import.to_string()) {
                    imports.push(import.to_string());
                }
            }

            for proto_enum in proto.enums.values() {
                if field.proto_type == proto_enum.name {
                    let import = format!("{}.proto", proto_enum.name.to_snake_case());
                    if !imports.contains(&import) {
                        imports.push(import);
                    }
                }
            }
        }

        imports.sort();
        imports
    }

    fn write_type_file(
        file_path: &Path,
        package: &str,
        imports: &[String],
        content: &impl std::fmt::Display,
    ) -> Result<()> {
        let mut file = fs::File::create(file_path)?;

        writeln!(file, "{}", Self::HEADER)?;
        writeln!(file)?;
        writeln!(file, "syntax = \"proto3\";\n")?;
        writeln!(file, "package {};\n", package)?;

        if !imports.is_empty() {
            for import in imports {
                writeln!(file, "import \"{}\";", import)?;
            }
            writeln!(file)?;
        }

        write!(file, "{}", content)?;

        Ok(())
    }
}

impl CodeWriter for ProtobufWriter {
    type GeneratedCode = GeneratedProto;

    fn write_single_file(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let file_path = self.output_file_path(output_dir);
        let mut file = fs::File::create(&file_path)?;

        writeln!(file, "{}", Self::HEADER)?;
        writeln!(file)?;
        write!(file, "{}", code)?;

        println!(
            "Generated Protocol Buffer definitions: {}",
            file_path.display()
        );

        Ok(vec![file_path])
    }

    fn write_single_module(
        &self,
        code: &Self::GeneratedCode,
        output_dir: &Path,
        _config: &CodegenConfig,
    ) -> Result<Vec<PathBuf>> {
        self.ensure_output_dir(output_dir)?;

        let mut written_files = Vec::new();

        for proto_enum in code.enums.values() {
            let file_path = output_dir.join(format!(
                "{}.{}",
                proto_enum.name.to_snake_case(),
                self.file_extension()
            ));
            Self::write_type_file(&file_path, &code.package, &[], proto_enum)?;
            written_files.push(file_path);
        }

        for proto_message in code.messages.values() {
            let file_path = output_dir.join(format!(
                "{}.{}",
                proto_message.name.to_snake_case(),
                self.file_extension()
            ));
            let imports = Self::collect_message_imports(proto_message, code);
            Self::write_type_file(&file_path, &code.package, &imports, proto_message)?;
            written_files.push(file_path);
        }

        println!(
            "Generated {} Protocol Buffer files in {}",
            written_files.len(),
            output_dir.display()
        );

        Ok(written_files)
    }

    fn format_preview(&self, code: &Self::GeneratedCode) -> String {
        format!("{}\n\n{}", Self::HEADER, code)
    }

    fn file_extension(&self) -> &str {
        "proto"
    }

    fn default_filename(&self) -> &str {
        "schema"
    }
}
